### ISSUE TITLE
Sorting: TUI supports 3-mode sorting, whereas coreBOS only has 2-mode sorting.

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#1035]
TUI supports 3-mode sorting, whereas coreBOS only has 2-mode sorting. In coreBOS, when you click on a column you can sort ascending or descending, then you cannot undo that, it will always be sorted until you click on another column, but in TUI we can click 3 times to get a "no sorting" state. This is not supported now, we must support it. If you look at the calls, you will see that it sends

* sortAscending=false
* sortAscending=true
* no sortAscending parameter

**Comment by Luke1982** [comment]
This needs some more attention. The [call](https://github.com/tsolucio/corebos/blob/denormlv/modules/Vtiger/ExecuteFunctions.php#L405) to `getListViewJSON` includes the `$orderBy` param but when I look at the actual function body, that parameter is never used since the code in `ExecuteFunctions.php` stores the sorting in the session right before calling the `getListViewJSON` function. The actual `getListViewJSON` function uses either the instance order-by or gets it from the session that was set just before that in `ExectuteFunctions.php`.

@joebordes when the sorting is not passed to the fetch, e.g. the sorting is forced to 'default', how should we sort the results? How do we force the code to select the 'default' order? I think that would be created_time sorting ascending?

**Comment by joebordes** [comment]
I would expect no sorting at all in the query, let the database do whatever it prefers

**Comment by Luke1982** [comment]
That would be as simple as just not adding the order by clause to the query [here](https://github.com/tsolucio/corebos/blob/19a589dfa83c11636660aba53f0bd1739cf942b5/include/ListView/ListViewJSON.php#L107-L109) when the query parameter is not present. But still I think the function should be fixed since it has a parameter that's never used.
