### ISSUE TITLE
Move CSS for action column to CSS file

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#1036]
https://github.com/tsolucio/corebos/blob/19a589dfa83c11636660aba53f0bd1739cf942b5/include/js/ListViewJSON.js#L366-L371
We use 5 lines of code here to set some CSS on the action column. I feel we should move this logic to a CSS file since I feel it belongs there, not here.

**Comment by Luke1982** [comment]
The same goes for these two blocks:
https://github.com/tsolucio/corebos/blob/denormlv/include/js/ListViewJSON.js#L378-L385

**Comment by denaldhushi** [comment]
Moved: https://github.com/tsolucio/corebos/commit/e1346cfd71c651a1a5e836e7f949e18021d61d0b
