### ISSUE TITLE
Use generators on database result loops

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#1070]
We very often use this construction:
```php
$r = $adb->pquery("SOME QUERY", array('param'));
while ($row = $adb->fetch_array($r)) {
    // do stuff with $row
}
```
Which is quite memory intensive. We can very easily switch to a generator, which would increase speed and decrease memory consumption a **lot**:
```php
$r = $adb->pquery("SOME QUERY", array('param'));
foreach (rowGenerator($r) as $row) {
    // do stuff with $row
}
function rowGenerator($r) {
	global $adb;
	while ($row = $adb->fetch_array($r)) {
		yield $row;
	}
}
```
What the generator does, is keep only the current iteration in memory, in stead of loading in the entire array and then looping and returning. I've seen this generate excel reports that ran into high memory limits before, generated in seconds after implementing this.

**Comment by joebordes** [comment]
very interesting. let me do some tests and get back to you

**Comment by joebordes** [comment]
I added this method to our database abstraction layer and a unit test to make sure it works

https://github.com/tsolucio/coreBOSTests/commit/0d455fa682f87fbd83e4755c5c0df65402e84e12

then used it to implement a script that lists the modules in an install

https://github.com/tsolucio/corebos/commit/277519512ed57eb6e716f5d6a4efd7eb53aee7d9#diff-25a70e673c2e61603edb6cf5876eb662a2849598598338aabacfbb538ba630cdR99

we will be able to start using this very soon and will gradually migrate the old structure to the new one

thanks!
