### ISSUE TITLE
Error : fieldname in general.js

### ISSUE THREAD

**Issue by mslokhat** [tsolucio/corebos#108]
Hi,
using latest code (no custom code , using MajorLabel Theme) : 
Uncaught ReferenceError: fieldname is not defined
doformValidation @ general.js?v=5.5.0:1127
dtlviewModuleValidation @ dtlviewajax.js:486
dtlViewAjaxSave @ dtlviewajax.js:147
onclick @ index.php?action=DetailView&module=Contacts&parenttab=Marketing&record=2&activity_mode=&viewname=0&…:1479

**Comment by Luke1982** [comment]
I'll dig into this as soon as I can.

**Comment by mslokhat** [comment]
the issue appears also on softed theme
seems that the fieldname variable (which is an array) is not initialized

**Comment by joebordes** [comment]
Can you please indicate the exact steps to reproduce the problem?  I can't seem to get it.

**Comment by mslokhat** [comment]
Seems the error gone by itself : 
. i was using the MajorLabel theme
when going to a contact, detailview-> edit portal user, set yes, and save the error appear

i have changed to softed , it appears at the beginning (same field) , now, the save works
i have revert back to majorlabel and the save works , no more error

sorry, like a ghost appears and disappear

**Comment by joebordes** [comment]
Most probably browser javascript caché issue
It is really important to clear the cache after each update as there is a lot of javascript

Thanks for informing
