### ISSUE TITLE
when you have a lot dashboards system not allowed add more widgets

### ISSUE THREAD

**Issue by slemernet** [tsolucio/corebos#1105]
When you have more a 100 users, active and/or inactive" and each user has your own dashboard system stop to add a new widgets in any user

Is possible add default widgets, but windows like as module, report and note system not "Unable to add homestuff! Please try again"

Perhaps the good idea, allowed saved dashboard for profile too, because normally, same profile, has same dashboard for default

**Comment by slemernet** [comment]
In fact, my system it happened that the system updated the link table and didn't create the widget

So each new widget generated an error

correcting the index table to the correct value worked again

maybe including a check would avoid this error

**Comment by joebordes** [comment]
thanks!
