### ISSUE TITLE
Records cannot be deleted. 

### ISSUE THREAD

**Issue by dfanaei** [tsolucio/corebos#1129]
Hi,
When I try to delete a record (for example: Organization, or Contact) it gives me an error "CSRF Error" "Illegal request". 
Can you please tell me a solution for this? 
Regards,

**Comment by dfanaei** [comment]
ok, so I figured out what the issue was just now. 
I installed a SSL certificate right after I installed CoreBOS. 
CoreBOS was installed with HTTP but the CRM was forcing HTTPS. 
I had to reinstall CoreBOS again and this time choose HTTPS in the installation guide. 
It would be good if you could let us know how to change the default URL without reinstalling, just in case somebody makes the same mistake.

**Comment by joebordes** [comment]
Hi,

Yes, that sounds correct, CSRF will trigger if the URL in the browser does not match the URL in the `$site_URL` in the configuration file. So, next time all you have to do is open the file config.inc.php, look for $site_URL and change it accordingly. No need to install again.

https://github.com/tsolucio/corebos/blob/master/config.template.php#L41

Security... a necessary evil

Thanks for sharing
