### ISSUE TITLE
Document Template not replacing default template

### ISSUE THREAD

**Issue by dfanaei** [tsolucio/corebos#1135]
I have created a document template for the invoice module. 
When I upload it in the documents, Application Template is chosen, The template check box is checked, I have even entered a version number. 
The template is setup using Open Office in windows with all the labels and everything setup properly. 
However, It doesn't export to pdf using the new template. 
Is there a known solution for this?

**Comment by dfanaei** [comment]
Also, It doesn't create a PDF in GenDoc. 
I have installed Libreoffice and Unoconv already.



This is the Debug: 

storage/2021/September/week2/8413_Invoice_Template.odt Init Compile
Parameters
array ( 'ID' => '8415', 'MODULE' => 'Invoice', 'ROOT' => NULL, 'DOCID' => NULL, )
storage/2021/September/week2/8413_Invoice_Template.odt START Compile 0.0031478404998779
COMPILE TEXT
array ( 'TEXT' => ' ', 'ID' => '8415', 'MODULE' => 'Invoice', )
storage/2021/September/week2/8413_Invoice_Template.odt START Styles 0.0031929016113281
storage/2021/September/week2/8413_Invoice_Template.odt START toGenDoc 0.0038058757781982
COMPILE TEXT
array ( 'TEXT' => 'To:', 'ID' => '8415', 'MODULE' => 'Invoice', )
COMPILE TEXT
array ( 'TEXT' => '{Invoice.account_id}', 'ID' => '8415', 'MODULE' => 'Invoice', )
Markers found
array ( 0 => 'Invoice.account_id', )
retrieve_from_db: Invoice.account_id with Invoice(8415)
REPLACE WITH: 8,411
COMPILE TEXT
array ( 'TEXT' => '{Invoice.bill_street}', 'ID' => '8415', 'MODULE' => 'Invoice', )
Markers found
array ( 0 => 'Invoice.bill_street', )
retrieve_from_db: Invoice.bill_street with Invoice(8415)
REPLACE WITH: test st
COMPILE TEXT
array ( 'TEXT' => '{Invoice.bill_city},{Invoice.bill_state},{Invoice.bill_country} {Invoice.bill_code}', 'ID' => '8415', 'MODULE' => 'Invoice', )
Markers found
array ( 0 => 'Invoice.bill_city', 1 => 'Invoice.bill_state', 2 => 'Invoice.bill_country', 3 => 'Invoice.bill_code', )
retrieve_from_db: Invoice.bill_city with Invoice(8415)
REPLACE WITH: test
retrieve_from_db: Invoice.bill_state with Invoice(8415)
REPLACE WITH: test
retrieve_from_db: Invoice.bill_country with Invoice(8415)
REPLACE WITH: test
retrieve_from_db: Invoice.bill_code with Invoice(8415)
REPLACE WITH: test
COMPILE TEXT
array ( 'TEXT' => '{Contacts.firstname}{Contacts.lastname}', 'ID' => '8415', 'MODULE' => 'Invoice', )
Markers found
array ( 0 => 'Contacts.firstname', 1 => 'Contacts.lastname', )
retrieve_from_db: Contacts.firstname with Invoice(8415)
retrieve_from_db: Contacts.firstname with Contacts(0)
REPLACE WITH:
retrieve_from_db: Contacts.lastname with Invoice(8415)
retrieve_from_db: Contacts.lastname with Contacts(0)
REPLACE WITH:
COMPILE TEXT
array ( 'TEXT' => 'From:', 'ID' => '8415', 'MODULE' => 'Invoice', )
COMPILE TEXT
array ( 'TEXT' => '{cbCompany.companyname}', 'ID' => '8415', 'MODULE' => 'Invoice', )
Markers found
array ( 0 => 'cbCompany.companyname', )
retrieve_from_db: cbCompany.companyname with Invoice(8415)
REPLACE WITH: Broadway Cabinets & Countertops
COMPILE TEXT
array ( 'TEXT' => '{cbCompany.phone}', 'ID' => '8415', 'MODULE' => 'Invoice', )
Markers found
array ( 0 => 'cbCompany.phone', )
retrieve_from_db: cbCompany.phone with Invoice(8415)
REPLACE WITH: 604 564 9222
COMPILE TEXT
array ( 'TEXT' => '{cbCompany.address}', 'ID' => '8415', 'MODULE' => 'Invoice', )
Markers found
array ( 0 => 'cbCompany.address', )
retrieve_from_db: cbCompany.address with Invoice(8415)
REPLACE WITH: 5291 Imperial St
COMPILE TEXT
array ( 'TEXT' => '{cbCompany.city}, {cbCompany.state}, {cbCompany.country} {cbCompany.postalcode}', 'ID' => '8415', 'MODULE' => 'Invoice', )
Markers found
array ( 0 => 'cbCompany.city', 1 => 'cbCompany.state', 2 => 'cbCompany.country', 3 => 'cbCompany.postalcode', )
retrieve_from_db: cbCompany.city with Invoice(8415)
REPLACE WITH: Burnaby
retrieve_from_db: cbCompany.state with Invoice(8415)
REPLACE WITH: BC
retrieve_from_db: cbCompany.country with Invoice(8415)
REPLACE WITH: Canada
retrieve_from_db: cbCompany.postalcode with Invoice(8415)
REPLACE WITH: V5J 1E5
COMPILE TEXT
array ( 'TEXT' => 'Qty', 'ID' => '8415', 'MODULE' => 'Invoice', )
COMPILE TEXT
array ( 'TEXT' => 'Description', 'ID' => '8415', 'MODULE' => 'Invoice', )
COMPILE TEXT
array ( 'TEXT' => 'Rate', 'ID' => '8415', 'MODULE' => 'Invoice', )
COMPILE TEXT
array ( 'TEXT' => 'Amount', 'ID' => '8415', 'MODULE' => 'Invoice', )
FOREACH -- Condition: InventoryDetails ID: 8415 MODULE: Invoice

FOREACH -- Condition: Products ID: 8416 MODULE: InventoryDetails

COMPILE TEXT
array ( 'TEXT' => '{InventoryDetails.quantity}', 'ID' => 8416, 'MODULE' => 'InventoryDetails', )
Markers found
array ( 0 => 'InventoryDetails.quantity', )
retrieve_from_db: InventoryDetails.quantity with InventoryDetails(8416)
REPLACE WITH: 1.00
IFEXIST -- Condition: Products ID: 8416 MODULE: InventoryDetails

retrieve_from_db: Products with InventoryDetails(8416)
COMPILE TEXT
array ( 'TEXT' => '{Products.productname}', 'ID' => 8416, 'MODULE' => 'InventoryDetails', )
Markers found
array ( 0 => 'Products.productname', )
retrieve_from_db: Products.productname with InventoryDetails(8416)
retrieve_from_db: Products.productname with Products(8414)
REPLACE WITH: Test Product
COMPILE TEXT
array ( 'TEXT' => '{InventoryDetails.description}', 'ID' => 8416, 'MODULE' => 'InventoryDetails', )
Markers found
array ( 0 => 'InventoryDetails.description', )
retrieve_from_db: InventoryDetails.description with InventoryDetails(8416)
REPLACE WITH:
COMPILE TEXT
array ( 'TEXT' => '{InventoryDetails.listprice}', 'ID' => 8416, 'MODULE' => 'InventoryDetails', )
Markers found
array ( 0 => 'InventoryDetails.listprice', )
retrieve_from_db: InventoryDetails.listprice with InventoryDetails(8416)
REPLACE WITH: 1,000.00
COMPILE TEXT
array ( 'TEXT' => '{InventoryDetails.linetotal}', 'ID' => 8416, 'MODULE' => 'InventoryDetails', )
Markers found
array ( 0 => 'InventoryDetails.linetotal', )
retrieve_from_db: InventoryDetails.linetotal with InventoryDetails(8416)
REPLACE WITH: 1,000.00
COMPILE TEXT
array ( 'TEXT' => 'Subtotal', 'ID' => '8415', 'MODULE' => 'Invoice', )
COMPILE TEXT
array ( 'TEXT' => '{Invoice.hdnSubTotal}', 'ID' => '8415', 'MODULE' => 'Invoice', )
Markers found
array ( 0 => 'Invoice.hdnSubTotal', )
retrieve_from_db: Invoice.hdnSubTotal with Invoice(8415)
REPLACE WITH: 1,000.00
COMPILE TEXT
array ( 'TEXT' => 'Tax', 'ID' => '8415', 'MODULE' => 'Invoice', )
COMPILE TEXT
array ( 'TEXT' => '{Invoice.sum_taxtotal}', 'ID' => '8415', 'MODULE' => 'Invoice', )
Markers found
array ( 0 => 'Invoice.sum_taxtotal', )
retrieve_from_db: Invoice.sum_taxtotal with Invoice(8415)
REPLACE WITH: 0.00
COMPILE TEXT
array ( 'TEXT' => 'Total', 'ID' => '8415', 'MODULE' => 'Invoice', )
COMPILE TEXT
array ( 'TEXT' => '{Invoice.hdnGrandTotal}', 'ID' => '8415', 'MODULE' => 'Invoice', )
Markers found
array ( 0 => 'Invoice.hdnGrandTotal', )
retrieve_from_db: Invoice.hdnGrandTotal with Invoice(8415)
REPLACE WITH: 1,000.00
COMPILE TEXT
array ( 'TEXT' => 'All cheques payable to: {cbCompany.companyname}', 'ID' => '8415', 'MODULE' => 'Invoice', )
Markers found
array ( 0 => 'cbCompany.companyname', )
retrieve_from_db: cbCompany.companyname with Invoice(8415)
REPLACE WITH: Your company
COMPILE TEXT
array ( 'TEXT' => 'Terms and Conditions:', 'ID' => '8415', 'MODULE' => 'Invoice', )
COMPILE TEXT
array ( 'TEXT' => '{Invoice.terms_conditions}', 'ID' => '8415', 'MODULE' => 'Invoice', )
Markers found
array ( 0 => 'Invoice.terms_conditions', )
retrieve_from_db: Invoice.terms_conditions with Invoice(8415)
REPLACE WITH: - Unless otherwise agreed in writing by the supplier all invoices are payable within thirty (30) days of the date of invoice, in the currency of the invoice, drawn on a bank based in India or by such other method as is agreed in advance by the Supplier.

- All prices are not inclusive of VAT which shall be payable in addition by the Customer at the applicable rate.
END GenDOC 0.073521852493286 s
Post processing No Index

**Comment by joebordes** [comment]
I suppose you were missing the PDF configuration steps and I understand you got it working, right?

**Comment by dfanaei** [comment]
Yes, I realized later on that I had to go to the settings and enable the Gendoc for the modules and then activate the PDF. 
Then, I also had to hide the Default PDF links through the business actions module. 
All good now.
Cheers,
