### ISSUE TITLE
Adding Terms and Conditions to Service Contracts

### ISSUE THREAD

**Issue by dfanaei** [tsolucio/corebos#1136]
Hi, I am trying to add the terms and conditions to the service contracts the same way it appears in invoice or quote module. 
I can add the text area and also the related module field where you can choose which terms and condtions. However, I cannot figure out how to make it automatically add the chosen terms and condition into the text area above it. 
And to add, once the issue above is fixed, can we somehow make it choose multiple terms and conditons and add it below eachother?

**Comment by dfanaei** [comment]
So I have tried adding a business map to do this using the code below. but it doesn't work. So I believe I am doing it wrong. 
cf_1162 = the field that I created in service contract to choose the right terms and conditions
cf_1161 = The text area in the service contract where it is supposed to copy and paste the value of the t&c field of the terms and conditions. 


<map>
  <originmodule>
    <originname>ServiceContracts</originname>
  </originmodule>
<dependencies>
<dependency>
    <field>cf_1162</field>
    <actions>
        <function>
            <name>fieldDep_GetField</name>
            <parameters>
              <parameter>tandc</parameter>
              <parameter>cf_1161</parameter>
            </parameters>
        </function>
    </actions>
</dependency>
</dependencies>
</map>

**Comment by joebordes** [comment]
Very nice! you are almost there!

I don't remember why right now but the function call requires an additional "field" directive in the map. Try like this

```xml
<map>
  <originmodule>
    <originname>ServiceContracts</originname>
  </originmodule>
<dependencies>
<dependency>
    <field>cf_1162</field>
    <actions>
        <function>
            <field>cf_1161</field>
            <name>fieldDep_GetField</name>
            <parameters>
              <parameter>tandc</parameter>
              <parameter>cf_1161</parameter>
            </parameters>
        </function>
    </actions>
</dependency>
</dependencies>
</map>
```

**Comment by dfanaei** [comment]
Thanks @joebordes  . 
This seems also not to work. 
As you can see in the first screenshot, I have created the business map. 
![Screenshot 2021-09-19 144133](https://user-images.githubusercontent.com/29267557/133944009-8e8569c5-abf8-4f86-bd2b-acd0e05de25a.jpg)

and in the second screenshot, I have chosen the Terms and Condition that is supposed to be copied into the service contract. But it is still blank. 
![2](https://user-images.githubusercontent.com/29267557/133944043-2e6b88cd-b1fb-427c-9bf2-0abf93a34b5c.jpg)

**Comment by dfanaei** [comment]
Ok. So, I just found the solution. 
The reason it wasn't working was the Name of the Business Map. I figured this out as you pointed it out a couple of years ago as I had the same type of issue with another business map I was creating. 

The solution (in case if anybody else is facing the same problem):
The name of the business map must be   **_[MODULENAME]__FieldDependency**

All the best.
