### ISSUE TITLE
Mail Manager Related Records. Add to Existing

### ISSUE THREAD

**Issue by dfanaei** [tsolucio/corebos#1142]
In the Action Picklist in the mail manager (where it says Related Records), it only has options to add records. 
Is there a way to connect a received email to an existing record? or in other terms, add options like "connect to existing organization".

**Comment by joebordes** [comment]
I think this is supported already. If the "from" email can be found in the application, the list of actions shows you "Attach".

![Captura de pantalla de 2021-10-17 12-35-19](https://user-images.githubusercontent.com/1237191/137623509-fa99bfc5-406d-4651-9b41-7f361f0439e3.png)

**Comment by dfanaei** [comment]
Yes. but once you choose attach, where is it supposed to save it under? in the Email Module or Messages Module? 
Because, I am not seeing anything attached in the related organization (in "more information" tab).

**Comment by joebordes** [comment]
pull again and test this change:  https://github.com/tsolucio/corebos/commit/1d5ab5b5604ffddf113097f2b1964d1dceb58d9a

that should fix the issue
Let me know how it goes

**Comment by dfanaei** [comment]
Yes. works now. Great!
Did you just add Module Builder? I think this feature is now going to make CoreBOS from Great to Perfect! 
:-)

**Comment by joebordes** [comment]
Great!
Yes, I did! Actually Denald, Franceska, and Xhilda did all the work, but I agree almost perfect!  Enjoy!
