### ISSUE TITLE
Groups > Members of Entity not showing

### ISSUE THREAD

**Issue by dfanaei** [tsolucio/corebos#1148]
Hi again, 
as I try to add members to a group that I created, The "members of Entity" list is empty. 
It is not empty when I try to add users to a role. only empty when I try to add users to a group.

In case if the server info is needed,
I have upgraded the operating system, the php version is 7.4, all required and optional extensions are installed already. 
Everything in the php.ini is already changed based on the requirements.

I am not sure what is going on, but certain bugs exist in my corebos and I cannot figure out why. If you look at the other issues I have created here, you will see what I mean. 
My first installation of PHP was 7.0 thanks to Ondrej for removing all the updates for ubuntu 16.04 but now I upgraded to 18.04 and installed php 7.4. The issues still exist. 
Everything else other than the issues I created are working fine, so I'm not sure if the issue is coming from a missing extension or something. 
I would really appreciate your support. 
Thanks,

**Comment by joebordes** [comment]
have you applied all the corebos updates?
I just tried this in my install and it seems to be working

When you install corebos and after each update (git pull) you MUST go to corebos updater, click on load and then apply all. Have you done that?

**Comment by joebordes** [comment]
![image](https://user-images.githubusercontent.com/1237191/137565094-5e01a8cb-dfef-4a4b-a341-4f2ccacd1c24.png)

can you reproduce this issue in the online demo or give me exact steps to reproduce it?

**Comment by dfanaei** [comment]
Thanks for your reply @joebordes 
I just Updated it. The issue didn't get fixed. And I got some errors while updating.
![Screenshot 2021-10-15 165631](https://user-images.githubusercontent.com/29267557/137565603-e3a4547e-8037-4196-a1e3-51f7db471136.jpg)

**Comment by joebordes** [comment]
do the other options work?
group, role?
open the inspector on the list to see if you have some javascript error.
search for `var userNameArr=new` in the inspector Elements tab and share the definition (edit the user names if you need to)

**Comment by dfanaei** [comment]
This is the code when I search var userNameArr=new (I believe it's line 144 and 145)
![Screenshot 2021-10-16 015420](https://user-images.githubusercontent.com/29267557/137581237-6c9bb2ce-ecb3-4090-8df6-813d3ecc043a.jpg)

Error index.php:319
![indexphp319](https://user-images.githubusercontent.com/29267557/137581420-f5e869ac-2126-4eed-a218-afb15cbd18e9.jpg)

Error index.php:217 (the line is too long for screenshot so I paste it here instead)

`										<select id="memberType" name="memberType" class="small" onchange="showOptions()"> <option value="groups" selected>Groups</option> <option value="roles">Roles</option> <option value="rs">Roles and Subordinates</option> <option value="users">Users</option> </select> <input type="hidden" name="findStr" class="small">&nbsp;`

Let me know if I did it wrong.

**Comment by dfanaei** [comment]
Ok Thanks. Here is the List of the Roles.
![roles](https://user-images.githubusercontent.com/29267557/137581789-09bf67b0-06f7-4927-b1cd-b1c2dbabf2c7.jpg)

Senior Management
Sales Person
Production

**Comment by dfanaei** [comment]
Sure. Here you go
![database vtiger-role](https://user-images.githubusercontent.com/29267557/137613990-00fec5b4-7e6b-47cb-8afd-33a7e5bfc199.jpg)
.

**Comment by joebordes** [comment]
I found the error. Give me a little time to fix it.  Thanks!

**Comment by joebordes** [comment]
pull and give it a try when you can. Let me know how it goes
thanks!

**Comment by dfanaei** [comment]
Perfect. Works now. 
Thanks @joebordes for your amazing work.
