### ISSUE TITLE
How to generate demo data

### ISSUE THREAD

**Issue by ugintl** [tsolucio/corebos#1159]
I have just installed corebos. Good work. In fact, really good work. Other softwares try restrict in one way or other, but I am amazed after seeing the features corebos is offering for free. My question is:

How to generate demo data?

**Comment by joebordes** [comment]
:-)  Glad you like what you see!  Welcome to the project

The easiest way to get demo data is using the [test project](https://github.com/tsolucio/coreBOSTests) database. Delete the database that was created during the install and create it again with the same name, or drop all the tables inside the database. Then download the [coreBOSTests.sql database](https://github.com/tsolucio/coreBOSTests/tree/master/database) and load/import it into the empty database.

Finally, go to coreBOS updater, load and apply all.

Enjoy

**Comment by ugintl** [comment]
I think I found the problem. Not all tables are importing. The last table I see is `vtiger_sales_stage_seq` So what I did is that I copied the remaining tables and created another sql file and imported it, but I see below error while importing

```
Error

SQL query:

CREATE TABLE `vtiger_salesmanactivityrel` (
  `smid` int NOT NULL DEFAULT '0',
  `activityid` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`smid`,`activityid`),
  KEY `salesmanactivityrel_activityid_idx` (`activityid`),
  KEY `salesmanactivityrel_smid_idx` (`smid`),
  CONSTRAINT `fk_2_vtiger_salesmanactivityrel` FOREIGN KEY (`smid`) REFERENCES `vtiger_users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3

MySQL said: Documentation
#1215 - Cannot add foreign key constraint
```

**Comment by ugintl** [comment]
I am using mysql 5.7

**Comment by ugintl** [comment]
@joebordes Everything else is same. I dropped all tables which were created during install and then I imported the demo database. Before importing demo database, the site was working.

**Comment by joebordes** [comment]
use the command line

`mysql -u your_user -p your_database < coreBOSTests.sql`

**Comment by joebordes** [comment]
config.inc.php

$dbconfig > database settings
$site_URL
$root_directory

should be enough

going to close this issue, feel free to open another one (or reopen this one)
