### ISSUE TITLE
Forgot my admin password

### ISSUE THREAD

**Issue by ugintl** [tsolucio/corebos#1183]
I forgot my admin password. What should I do?

**Comment by slemernet** [comment]
http://corebos.org/documentation/doku.php?id=en:adminmanual:faq#how_can_i_reset_the_admin_user

**Comment by joebordes** [comment]
Thank you @slemernet :-)

@ugintl, this script you have in build/HelperScripts can do that too: https://github.com/tsolucio/corebos/blob/master/build/HelperScripts/reset_admin_pw

**Comment by ugintl** [comment]
@joebordes 1. What hash format I should use? I have searched online for md5 hash generator, but the format is like this. For example if my password is "admin", the md5 hash will be "21232f297a57a5a743894a0e4a801fc3"

2. WHat is the default admin password for demo content?

**Comment by joebordes** [comment]
use the values in the link slemernet sent:  user_password='$1$ad$hsl2KFybNRnbXBa.b.WWv.', crypt_type='MD5'
that is the MD5 value you need to set the admin password to `admin`

the default admin password for admin is `admin`

**Comment by joebordes** [comment]
:-)
