### ISSUE TITLE
PDF Export only contains empty files

### ISSUE THREAD

**Issue by partnerwerk** [tsolucio/corebos#1190]
I set up a new instance of Corebos with docker containers. I used the same settings as with previous installs having a separate docker container for unoconv. However when exporting an invoice to PDF I receive an empty file. Export to .odt works fine and it is also written into the folder cache/gendocoutput/Invoice. The empty pdf file is also prsent in that folder. When I am going into the docker container I can produce the full pdf with unoconv. What am I missing?

**Comment by xhildashazivari** [comment]
You can apply this change:
```php 
diff --git a/vtlib/thirdparty/network/HTTP/Request2/Adapter/Curl.php b/vtlib/thirdparty/network/HTTP/Request2/Adapter/Curl.php
index 8edf5d343..454e42269 100644
--- a/vtlib/thirdparty/network/HTTP/Request2/Adapter/Curl.php
+++ b/vtlib/thirdparty/network/HTTP/Request2/Adapter/Curl.php
@@ -392,6 +392,7 @@ class HTTP_Request2_Adapter_Curl extends HTTP_Request2_Adapter
             $canonicalName = implode('-', array_map('ucfirst', explode('-', $name)));
             $headersFmt[]  = $canonicalName . ': ' . $value;
         }
+        $headersFmt[] = "Transfer-Encoding:";
         curl_setopt($ch, CURLOPT_HTTPHEADER, $headersFmt);
 
         return $ch;
```
Meanwhile, we are working on a better solution.

**Comment by partnerwerk** [comment]
Thank you very much. It works again with this patch!

**Comment by joebordes** [comment]
added that patch to coreBOS

https://github.com/tsolucio/corebos/commit/efd9a7b46aa65dba86582cb4655f003059010ab0
