### ISSUE TITLE
Wrong Date Shown in Calendar for Projects

### ISSUE THREAD

**Issue by dfanaei** [tsolucio/corebos#1252]
looks like the wrong date is shown for projects.

as you see in the screenshot below the project start date is set for 23rd and target end date is set for 24th.
![image](https://user-images.githubusercontent.com/29267557/159379748-fc222abe-53f6-4836-ae14-b9335b602ec5.png)

but in the calendar it shows 22nd to 23rd.
![image](https://user-images.githubusercontent.com/29267557/159379839-a803ff36-c015-4320-a00b-81d15220484f.png)

**Comment by dfanaei** [comment]
Hi
Anyone else has this issue? I cannot find any solution as this is only happening with the projects module. 
Thanks,

**Comment by dfanaei** [comment]
thanks for your reply @xhildashazivari .
any specific steps to debug?

**Comment by joebordes** [comment]
can you reproduce it in the demo? that would permit us to see it failing.

**Comment by dfanaei** [comment]
ok so, it looks like it got fixed now but perhaps you might wanna check the code based on what fixed it (explained below). 

the Default application timezone was set to UTC. the User timezone was set to UTC-8 or America/Vancouver. 
All modules showed the correct time in the calendar except projects. it showed one day earlier. 
I went in the config.inc.php and changed the default timezone to america/vancouver and kept the user timezone to utc-8 (america/vancouver). 
This seemed to fix the issue for the project module time in the calendar. 
This made all the previous record times changed and pushed back but doesn't really matter in my case as the calendar is more important to work correctly for me. 
Please note, even though it got fixed, the project module was the only one that had this issue.

**Comment by joebordes** [comment]
great!!  that information should be enough for us to have a look and reproduce it. Thanks

[This article may be useful for you](https://blog.corebos.org/blog/timezone)
