### ISSUE TITLE
Business Mapping - PO to Payments - Non-Related Value

### ISSUE THREAD

**Issue by dfanaei** [tsolucio/corebos#1261]
I am trying to make the business action "add payment" for Purchase order to create a Payment record but also select a value from a custom picklist in the payment module. 
The picklist field name is called "Transaction Type" and I need it to automatically select the option that is called "Outbound". 

I could not find anything in the Documentation as this is not really a related field that needs to be mapped. it's basically a field that needs to be selected if the payment record is being created from a Purchase Order. 
I creating a business Map with the value below, but did not succeed. 

Is there a way to do this?

```xml
<map>
  <originmodule>
    <originname>PurchaseOrder</originname>
  </originmodule>
  <targetmodule>
    <targetname>CobroPago</targetname>
  </targetmodule>
  <fields>
    <field>
      <fieldname>cf_1250</fieldname> *** This is the Transaction Type Field in Payment Module****
      <Orgfields>
            <Orgfield>
                <OrgfieldName>Outbound</OrgfieldName>  *** This is value that needs to be selected ***
            </Orgfield>
        </Orgfields>
    </field>
  </fields>
</map>
```

Also, This didn't work: 

```xml
<map>
  <originmodule>
    <originname>PurchaseOrder</originname>
  </originmodule>
  <targetmodule>
    <targetname>CobroPago</targetname>
  </targetmodule>
  <fields>
    <field>
        <fieldname>cf_1250</fieldname>
        <Orgfields>
            <Orgfield>
                <OrgfieldName>Outbound</OrgfieldName>
                <OrgfieldID>CONST</OrgfieldID>
            </Orgfield>
        </Orgfields>
    </field>
  </fields>
</map>
```

Business Map Name: PurchaseOrder2CobroPago
Map Type: Field Set Mapping
Target Module: Payments

**Comment by mukadessharka** [comment]
Hi,
The business map is correct to some point, you have to add to the OrgfieldID to CONST

```
            <Orgfield>
                <OrgfieldName>Outbond</OrgfieldName>
                <OrgfieldID>CONST</OrgfieldID>
            </Orgfield>
```

Secondly, the Map Type, in this case, has to be `Mapping` which is used to do the mapping between the modules. 
And the third element that we had to change was the Business Action `Add Payment` because it doesn't support that business map. Referring to the documentation, we have to add the `cbfromid`  to that action on the Link URL  `&cbfromid=$RECORD$` and save the changes.

**Comment by dfanaei** [comment]
Perfect! Thanks @mukadessharka 
It worked.
