### ISSUE TITLE
Paging record history does not signal bounds anymore

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#1283]
When you reach the end of the record history paging, we used to have a popup that would tell you there was no more information. That doesn't work anymore, there is a console error with a JSON parse error and the AJAX call returns `NOTRACKRECORD`, which isn't valid JSON.

**Comment by joebordes** [comment]
That message is still there and is working correctly

![Captura de pantalla de 2022-05-20 00-14-14](https://user-images.githubusercontent.com/1237191/169413401-9dd5cfe6-0d8e-44c5-89d9-00923b8f0a80.png)

I think you may have some extra space or newline in some of your translation files that is breaking the response. Those are really pesky bugs to trace. try with the [find trailing spaces](https://github.com/tsolucio/corebos/blob/master/build/HelperScripts/find_trailing_space.php) to see if that is the issue. Ask for help as you need.

**Comment by Luke1982** [comment]
Wouldn't it be better if we just trimmed the [response](https://github.com/tsolucio/corebos/blob/master/modules/ModTracker/ModTrackerCommon.js#L138) before checking it? Seems like a more fail-safe thing to do, since I didn't change any translation files, nor is this string translated I think. Assuming the string will contain no leading or trailing spaces seems more perilous than just using the power of JavaScript to avoid these assumptions.

**Comment by joebordes** [comment]
that is not the issue, it isn't about this particular string having "noise" it is about adding a single space or new line ANYWHERE in the application. it breaks the whole thing, adding a trim here would make no difference

**Comment by Luke1982** [comment]
Well if a single space or newline can break things like this, I believe it is up to us as programmers to decide which data is correct and which isn't. In this case, two mysterious newlines have been entered before the word 'NOTRACKRECORD'. I haven't translated anything, and don't believe this string is translated at all. I think we should have the philosophy that trimmed data that ends up correctly should be correct.

**Comment by Luke1982** [comment]
The issue here is that two empty lines are added before the echo of `NOTRACKRECORD`, which happens on my production server, but not on my local test server. So definitely some server setup issue.

I do however disagree on you standpoint that it isn't our responsibility think about the different forms that our data may take. Of course we can't prepare for every edge-case, but there are a lot of things we can do. The fact that we can't control everything someone does or changes shouldn't change that, we still have a responsibility for what we can control in my view. I mean, your car manufacturer isn't going to not bother mounting the seatbelts just because you have the liberty to mount crappy used tires.

I think the application should be as agnostic as possible, as long as we can guarantee data integrity. As soon as we can't, we should fail with a bang and make it obvious something went wrong. So in this case: try to trim the string down and see if it ends up with what we expect, and if it doesn't: warn the user about a failure.

**Comment by joebordes** [comment]
the typical example where this happens is because someone has edited incorrectly config.inc.php adding a space or new line outside the PHP initial `<?php` or after the closing `?>`  

another typical example is where someone has uploaded a file via FTP nonbinary and they have added MSDOS EOL, that exrta ^M breaks PHP

this is why I told you to search for where that extra annoyance has been introduced using the program https://github.com/tsolucio/corebos/blob/master/build/HelperScripts/find_trailing_space.php

let me know if I can help

**Comment by joebordes** [comment]
about the task of catching this with the code itself. First try to find that extra character by hand, using the tool above and adding "echo"s all over the place (which is what I always end up doing

then think about how to automate that in some script to detect that auto-heal process and let's talk about it again. I am not closed to what you are saying but my current knowledge of the error makes me believe that the effort it takes to do that for the 10 cases I have had in the last 6 years doesn't make it worth the effort. It is just too easy to avoid completely and even to detect and fix when it does happen. GIT is your best friend.

Let me know how it goes

**Comment by Luke1982** [comment]
Will do, this installation is deployed by GIT and almost untouched. But I must have messed up something. Let me check and get back to you. One thing I would like to circle back to is the data format check I talked about in the blog Ii wrote a couple of years ago, about saving data.

**Comment by Luke1982** [comment]
Great tool, it was just a trailing space in config.inc.php
