### ISSUE TITLE
Master-Detail widget list doesn't sort on date

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#1284]
![Peek 2022-05-19 14-49](https://user-images.githubusercontent.com/8875222/169297131-57ea6fdc-7287-426e-834c-8bfee505866c.gif)

I want to allow users to sort on created_date, since sorting on record numbers can't be trusted (due to the prefix being saved in the same column), but the new editor seems to sort them randomly. The old relatedlist could do this.

**Comment by xhildashazivari** [comment]
Fixed by @denaldhushi
