### ISSUE TITLE
Inline editing a result in a filtered TUI grid resets the results

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#1289]
![Peek 2022-05-24 16-49](https://user-images.githubusercontent.com/8875222/170065546-fa5f981e-a274-453e-ba36-e50394c0ba04.gif)
As seen above:
- Open a list
- Filter the list
- Double click a field to edit
- Make a change
- Hit 'Enter' to save

You'd expect the result set to stay intact, but it re-loads the entire set after saving the change.

**Comment by xhildashazivari** [comment]
Fixed, thank you!
