### ISSUE TITLE
MasterDetail TUI editor allows you to open multiple fields for inline edit

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#1291]
![Peek 2022-05-24 17-21](https://user-images.githubusercontent.com/8875222/170072582-7752bbc7-5d20-4065-979e-4c995a79c649.gif)
As you can see, this leads to unexpected results. Maybe it would be better if opening one field up for inline editing, closes all the other ones?

**Comment by xhildashazivari** [comment]
It seems to work correctly for us. Do you have any console error?

**Comment by Luke1982** [comment]
No. Since I updated today, I can't reproduce this anymore. So let's wait and see.
