### ISSUE TITLE
Relatedlist query doesn't join on crmentity

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#1297]
I have a custom module called 'ServiceJob' that works on maintable `vtiger_crmentity`. It has a one to many relationship to Assets. After updating the application to the latest code, the relatedlist that lists 'ServiceJobs' on Assets doesn't work anymore, because the query has an error:
```sql
SELECT count(*) AS count 
	FROM vtiger_servicejob
    INNER JOIN ON vtiger_crmentity.crmid = vtiger_servicejob.servicejobid
    INNER JOIN vtiger_servicejobcf ON vtiger_servicejobcf.servicejobid = vtiger_servicejob.servicejobid
    INNER JOIN vtiger_assets ON (vtiger_assets.assetsid = vtiger_servicejob.related_asset_id)
    LEFT JOIN vtiger_users ON vtiger_users.id = vtiger_crmentity.smownerid
    LEFT JOIN vtiger_groups ON vtiger_groups.groupid = vtiger_crmentity.smownerid
    WHERE vtiger_crmentity.deleted=0
    AND vtiger_assets.assetsid = 3659
```
Notice on line 3 of the query the query tries to JOIN `vtiger_crmentity` without mentioning that table in the JOIN clause.

**Comment by joebordes** [comment]
look in the vtiger_entityname table for the row of this module, make sure the denormtable has vtiger_crmentity in it (or not)

**Comment by Luke1982** [comment]
![Screenshot_20220530_161200](https://user-images.githubusercontent.com/8875222/171009937-523afece-3c41-4a2c-9466-69cf358408c5.png)
This is the entry for this module in `vtiger_entityname`

**Comment by joebordes** [comment]
does your module have a `__construct()` that doesn't call the parent CRMEntity construct?

**Comment by Luke1982** [comment]
Yes, and that was the problem. Is that a new requirement for modules?
