### ISSUE TITLE
Reselling or redistributing

### ISSUE THREAD

**Issue by ugintl** [tsolucio/corebos#1329]
Is it allowed to resell or redistribute modified version of this software free or paid?

**Comment by joebordes** [comment]
Hi @ugintl 

coreBOS is distributed under [VPL](https://discussions.corebos.org/documentation/doku.php?id=en:devel:vpl11) license. It is a slightly modified version of [MPL](https://www.mozilla.org/en-US/MPL/1.1/annotated/) which permits you to use and redistribute the software as you wish freely.

We promote the usage and modification of the application, trying to make it as flexible and configurable as possible so you can adapt it to your needs while keeping in sync with the continuous development efforts we make. We are available to help and support your needs.

Note that each module can be distributed under different licenses. The most common one you can find is the [Vizsage](https://discussions.corebos.org/documentation/doku.php?id=en:devel:vizsage) which kindly asks you to give back some of the benefits you make. Consult the individual license of each module you download.

Join our [gitter group](https://gitter.im/corebos/discuss) and keep asking

welcome to coreBOS :-)

**Comment by ugintl** [comment]
@joebordes So does it also mean that I can use my own branding and sell it under my name? Like a propriety software?

**Comment by joebordes** [comment]
yes, correct, you can

would be nice if you shared some of the benefits of doing that to help us keep going ;-)

**Comment by ugintl** [comment]
@joebordes Understood 👍 If I do that then definitely. I always appreciate developers making such effort and then making their work open source. Just a general question. Does MIT license give me the same freedom?

**Comment by joebordes** [comment]
Yes, correct. MIT also permits that type of liberty
