### ISSUE TITLE
Attachment download with special characters

### ISSUE THREAD

**Issue by Netmees** [tsolucio/corebos#1350]
This is an issue that had been around since vtiger 5.4... downloads get INVALIDFILE on validation of the download name whe the file contains some accent or special character when corebos tries to generate the download link 

Also the Name of the have problems to generate the name when generating the$ATTACHNAME   and link on smarty MailOpen.tpl

**Comment by joebordes** [comment]
HI

First, make sure you are using UTF8 everywhere (config.inc.php and database) and share the exact steps to reproduce the issue.

Thanks

**Comment by Netmees** [comment]
it would be necesary to include {$ATTACHNAME|@urlencode:**'UTF-8'**} on MailOpen.tpl ?

**Comment by Netmees** [comment]
config and database are setup on utf8
$default_charset = 'UTF-8';

**Comment by joebordes** [comment]
I could not reproduce this. Feel free to repone with more details
