### ISSUE TITLE
Select2 component does not respect keyboard entry

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#1356]
![afbeelding](https://user-images.githubusercontent.com/8875222/191454777-1f055c5e-bd1b-4dc9-be89-c4b6bae0638e.png)
The select2 component that's being used in the column selector for the basic search does not open on focus / respect `downarrow` or `uparrow` keyboard input, like a normal `<select>` does.

**Comment by joebordes** [comment]
can't we just use normal/native select HTML elements? Why do we need to add all that JS code and modify these elements so much?

**Comment by Luke1982** [comment]
I don't know. I didn't implement this but on this matter I totally agree: a regular, LDS styled select would totally suffice here.

**Comment by joebordes** [comment]
I don't know either. This all started with the change in the advanced search where there is a bunch of code that changes the behavior of those picklists. I tried passing a task to convert them into simple picklists but it wasn't possible. I don't know why.

I suppose it is another area where we have to refactor everything.

**Comment by Luke1982** [comment]
This is not related to the advanced filter. I wrote that, including the picklist (LDSDropdown). That component implements keyboard navigation. This is the select field on the basic search, not the advanced search. It is a completely different thing.

**Comment by joebordes** [comment]
fixed with 4f7a8f1ff1e00750e51da4b8c7c368cb7c6bcb1e
