### ISSUE TITLE
Related Entity fields not available in advanced search

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#1358]
Related to #1356 

The directly related field must be available in the advanced search picklist. For example, Project Task must show the Project fields or Contacts must show the Accounts fields. I suppose this was also lost with the filter search option changes.

**Comment by denaldhushi** [comment]
@joebordes  I think the problem start from [getAdvancedSearchOptionArray](https://github.com/tsolucio/corebos/blob/master/include/ListView/ListViewController.php#L861-L905). This function return only module fields and not direct related fields. I suppose something is changed in backend where related fields aren't comming.

**Comment by Luke1982** [comment]
> Related to #1356
> 
> The directly related field must be available in the advanced search picklist. For example, Project Task must show the Project fields or Contacts must show the Accounts fields. I suppose this was also lost with the filter search option changes.

I don't think this happened when the advanced filter was upgraded. All I did was take the function that created an HTML string, and adjusted that so that it returns an array. If that doesn't do what it should, neither did the original.

**Comment by joebordes** [comment]
first attempt at a solution has been pushed 93751c24cb07284f26d66a163c71caa0995bce30

give it a try and get back
