### ISSUE TITLE
Report not translated fields correclty

### ISSUE THREAD

**Issue by slemernet** [tsolucio/corebos#1359]
When I use file pt.br_custom.php to translated some fields in project and project tasks, report shows label in english

![ReportProjectxProjectTasks](https://user-images.githubusercontent.com/47395137/191858191-84a6a167-5817-494c-b1c0-6950986e17e8.PNG)
[ProjectTask pt_br.custom.php.txt](https://github.com/tsolucio/corebos/files/9629634/ProjectTask.pt_br.custom.php.txt)
[Project pt_br.custom.php.txt](https://github.com/tsolucio/corebos/files/9629641/Project.pt_br.custom.php.txt)

Example: Field Description, should be translated to 'Atualização'

**Comment by joebordes** [comment]
I need to see the real label values of those two selected fields. Right click on the select box, inspect, open the "select" and find the "option" that defines that entry of the picklist. You will see the "option" has a "value" propery, paste here that value for both picklists, please

**Comment by slemernet** [comment]
![OPTION](https://user-images.githubusercontent.com/47395137/191866981-1e66ed0d-b434-4d96-912b-5c27ecac65bf.PNG)

That value?

**Comment by joebordes** [comment]
argh it isn't a select box anymore, now it is some combobox with magic inside :-/

we changed the whole search thing and made it much more complicated...

let me try to find some time to have a look :-(

**Comment by joebordes** [comment]
I understand that the "Description" field you selected is some custom field and that you have set the label of that field to "description", in lower case D???

The translation you have done of the standard Descrption field is working correctly, I don't know what is the label of the field that is working incorrectly. I suppose it will not work with a lowercase D. Set the label to some other value that is not so common. Share the label of the field that is failing.  Why didn't you set it directly to "Atualização"?

**Comment by slemernet** [comment]
I use label showed in layout editor (UI). I use first label, because that put "d" ...

description Área de texto 16777215
vtiger_crmentity:description:description:ProjectTask_Description:V~O

I normally try using pt_br.custom.php, when only one client  ask for label different as usual

**Comment by joebordes** [comment]
I don't understand how you created that field. Can you reproduce it in the demo, please?

**Comment by slemernet** [comment]
Not custom field, that´s default field - description in project task

**Comment by slemernet** [comment]
I change my pt_br.custom.php fot use "Description" with upercase "D", and works !
