### ISSUE TITLE
Evaluate math in number fields instantly

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#1364]
Maybe it's better to wait until LDS grid is implemented, but in any case: it would be cool if we could implement `mathjs` on N and NN fields. We could trigger on the blur event and evaluate the contents of the field. I often stumble on the case where I want to enter some number and pull up a calculator on the side (be that a software calculator). Would be very nice if we could just do all of that in the application.

https://mathjs.org/

**Comment by joebordes** [comment]
Can't you do that already?

- Upload the library somewhere in your project
- Add a business action that loads the library
- Add a field dependency that triggers your javascript

or that isn't possible?

**Comment by Luke1982** [comment]
I have no idea, but that sure sounds possible. It was more along the lines of a 'nice to have' in the main repository.
