### ISSUE TITLE
Fatal Error in Documents listview

### ISSUE THREAD

**Issue by lorenzogreco** [tsolucio/corebos#1384]
This when i try to open Documents starting from Menu
Fatal error: Uncaught Error: Call to a member function getModuleColumnsList() on null in /home/XXXXXX/modules/Documents/FoldersListView.php:266 Stack trace: #0 /home/xxxxxx/modules/Documents/ListView.php(18): include_once() #1 /home/xxxxxx/modules/Documents/index.php(13): include_once('/home/xxxxxx...') #2 /home/xxxxxx/index.php(471): include_once('/home/gogo/vt.g...') #3 {main} thrown in /home/xxxxxx/modules/Documents/FoldersListView.php on line 266

coreBOS 8.0  (d6be0b01020221005)

FYI
regards
Lorenzo Greco

**Comment by joebordes** [comment]
Update and try please

**Comment by lorenzogreco** [comment]
It works now
seems ok.
Tnx
Lorenzo

**Comment by lorenzogreco** [comment]
It works now

Great Joe

Tnx

Lorenzo

 

Da: Joe Bordes ***@***.***> 
Inviato: mercoledì 19 ottobre 2022 15:54
A: tsolucio/corebos ***@***.***>
Cc: lorenzogreco ***@***.***>; Author ***@***.***>
Oggetto: Re: [tsolucio/corebos] Fatal Error in Documents listview (Issue #1384)

 

Update and try please

**Comment by joebordes** [comment]
:-)
