### ISSUE TITLE
Basic search term does not search in translated fields

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#1406]
When I want to search in, for instance, business actions, and I want to get all records that apply to SalesOrders, I can't search for my translation of 'SalesOrders', I still need to enter the English form.

**Comment by joebordes** [comment]
there is a changeset, picklist_translations, open it, unblock it, undo it, apply it again. try and let me know

**Comment by Luke1982** [comment]
I have multiple:
![afbeelding](https://user-images.githubusercontent.com/8875222/200310371-55bd7162-1753-4e36-b9a7-3dfc919f9979.png)
All have been executed

**Comment by joebordes** [comment]
as in. you ublocked it, undid it, and applied it again, right?
