### ISSUE TITLE
Advanced search stuck

### ISSUE THREAD

**Issue by lorenzogreco** [tsolucio/corebos#1429]
![image](https://user-images.githubusercontent.com/19155538/204083309-cb652c2b-cef2-4e9d-9435-0b80eb960798.png)

new condition not works

advancefilter.js:1270 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at Operations.getOps (advancefilter.js:1270:42)
    at Operations.getComboBox (advancefilter.js:1226:21)
    at Cond.setOps (advancefilter.js:1129:12)
    at Cond.init (advancefilter.js:927:9)
    at Group.addCond (advancefilter.js:771:9)
    at Group.init (advancefilter.js:717:10)
    at Group.add (advancefilter.js:617:7)
    at cbAdvancedFilter.init (advancefilter.js:107:11)
    at new cbAdvancedFilter (advancefilter.js:43:8)
    at index.php?action=index&module=Contacts:162:27

**Comment by joebordes** [comment]
this works for me. can you open the database, go to the vtiger_field table, search for the row with firstname for contacts and tell me what value is in the typeofdata column for that row?

**Comment by lorenzogreco** [comment]
here you are: V~O
first name for contacts

**Comment by joebordes** [comment]
that is correct
can you clear the cache?

**Comment by lorenzogreco** [comment]
Browser cache?
i tryed, and i tryed also with an other notebook
same mistake

**Comment by maliknajjar** [comment]
do you have the latest version of corebos?

**Comment by lorenzogreco** [comment]
coreBOS 8.0  (d8b971ff920221128)

**Comment by maliknajjar** [comment]
can you try to press ctrl, shift and R .. and try again?

**Comment by lorenzogreco** [comment]
>can you try to press ctrl, shift and R .. and try again?  
tryed same error

For your information i have  Global Variable "Application_ListView_SearchColumns"  set to 1

**Comment by maliknajjar** [comment]
it works fine with me after I added the (Application_ListView_SearchColumns) GlobalVariable.
what browser are you using?

**Comment by lorenzogreco** [comment]
Chrome
firefox
Microsoft Edge

**Comment by lorenzogreco** [comment]
Perhaps is a my problem in global variable, 
for example i can't choose to set up Application_ListView_FilterPanel_Open
this option isn't show in the list.

**Comment by joebordes** [comment]
have you applied all in corebos updater?

**Comment by lorenzogreco** [comment]
Yes i did, ( executed all except 3 continuous 02 044 080)
I've a lot of system update NO
 but now i  tryed to re-apply  cbupd-0000044  ( contionuos) and Application_ListView_FilterPanel_Open is visible
but the problems with filter is the same.

**Comment by joebordes** [comment]
vtiger_field typeofdata was missing a letter, maybe a good idea to add a default `V` if it isn't there but it should be there always...
