### ISSUE TITLE
Impossible to turn off   ClickHouse Activation

### ISSUE THREAD

**Issue by lorenzogreco** [tsolucio/corebos#1430]
![image](https://user-images.githubusercontent.com/19155538/204083510-f81d95eb-5e6f-4118-a50e-1b22d278eb59.png)

If Active is set to on, push the button to set active to off, press Save, it returns ON.
the only way to set turn off this module is to go directly in DB
table cb_setting ,  field setting_key  value=clickhouse_isactive setting_value=0

**Comment by joebordes** [comment]
Hi

Could we have just fixed this today with this commit I just accepted:  https://github.com/tsolucio/corebos/commit/74d6f7fd53e7c51e965a3e9ab95a9ecbefeb2df0 

??

**Comment by lorenzogreco** [comment]
i 've seen but..
Updating d728797c3..74d6f7fd5
Fast-forward
 include/integrations/clickhouse/settings.php | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

 git pull
Already up to date.
and i have the same error
i've just tested with chrome and Firefox to be sure cache was empty
Lorenzo

**Comment by joebordes** [comment]
reproduced this will look into it asap.  thanks!

**Comment by joebordes** [comment]
in the mean time you can deactivate it if you leave the fields filled in

**Comment by joebordes** [comment]
I just accepted a PR that should fix this issue, can you please give it a try and let me know?

**Comment by lorenzogreco** [comment]
now it works,
ad if the fields are empy is impossible to turn on.
It's OK

**Comment by joebordes** [comment]
great
