### ISSUE TITLE
Upgrade json editor to improve ui for developer  :enhancement

### ISSUE THREAD

**Issue by Netmees** [tsolucio/corebos#1437]
its very complicated to edit json files on buisines actios, etc when its a large file

it would be better to have a editor like https://github.com/josdejong/svelte-jsoneditor to make easyer handle big json files

**Comment by Netmees** [comment]
:enhancement:

**Comment by Netmees** [comment]
https://codesandbox.io/s/svelte-jsoneditor-vue-toln3w

**Comment by joebordes** [comment]
JSON files?  you mean XML files in Business maps, no?

anyway, we need a vanilla javascript library, we are not going to add framework library dependencies.
