### ISSUE TITLE
workflow "use function" button on workflow condition not working

### ISSUE THREAD

**Issue by Netmees** [tsolucio/corebos#1442]
on setting the button on for creating an expresission popup windows closes and back without giving any error on developer tool on browser

system updated daily

**Comment by joebordes** [comment]
share the steps you follow to create the popup, please

**Comment by Netmees** [comment]
i mean de the window to edit the condition witching between text / field / expression

**Comment by Netmees** [comment]
i have taken a look at https://demo.corebos.com and its working good.... and choose between the functions are shown.... 

the system its a clone from the main git and updated from github with git pull... for testing purposes....

![Screenshot_20221213_183554](https://user-images.githubusercontent.com/78955281/207405090-4e7ec0d6-afd6-4bdb-9b60-300ab31141d2.png)

**Comment by joebordes** [comment]
it seems to be working correctly on my development install
let me update the demo and you can try again there

**Comment by Netmees** [comment]
on demo its working ok Joe....

**Comment by joebordes** [comment]
yes, but demo is not up to date

**Comment by joebordes** [comment]
I updated the demo. It seems to be working still. Give it a try

**Comment by Netmees** [comment]
now that you are over here... take a look a what i am doing  to mail manager
![mailmanager](https://user-images.githubusercontent.com/78955281/207406530-92268f5e-3f24-4a2f-a67e-4d65dae2a390.png)

**Comment by joebordes** [comment]
interesting

**Comment by Netmees** [comment]
much better with new icons... :-D

**Comment by Netmees** [comment]
it would be usefull to have a section on configuration to handle the folders....

**Comment by Netmees** [comment]
yeah.... its working on the demo....
and the problem its on a clone on te main branch... so.... has be the same code....
git pulled everyday.....

**Comment by Netmees** [comment]
i am gonna keep on searchin whats its interacting on my configuration and update the ticket... maibe some smarty devel enabled before for testing ( but dissabled now ) or some global variable....

**Comment by Netmees** [comment]
as i remember after i clone the git i send the comand to upgrade third party libraries 
git submodule update 
maibe the problem comes from there....

**Comment by Netmees** [comment]
this is the actual composer 

{
    "require": {
        "symfony/console": "5.1.0",
        "twilio/sdk": "5.37.0",
        "tecnickcom/tcpdf": "6.3.2",
        "knplabs/gaufrette": "0.9.0",
        "gaufrette/azure-blob-storage-adapter": "0.6.0",
        "gaufrette/ftp-adapter": "0.4.0",
        "guzzlehttp/psr7": "1.6.1",
        "guzzlehttp/promises": "1.3.1",
        "guzzlehttp/guzzle": "6.4.1",
        "onelogin/php-saml": "3.4.1",
        "laminas/laminas-cache": "2.10.3",
        "laminas/laminas-json": "3.1.2",
        "laminas/laminas-serializer": "2.9.1",
        "phpseclib/phpseclib": "2.0.31",
        "psr/log": "1.1.1",
        "firebase/php-jwt": "5.0.0",
        "google/auth": "1.6.0",
        "google/apiclient-services": "0.120",
        "google/apiclient": "2.4.0",
        "laminas/laminas-zendframework-bridge": "1.1.1",
        "laminas/laminas-stdlib": "3.3.1",
        "psr/container": "1.0.0",
        "laminas/laminas-servicemanager": "3.5.1",
        "laminas/laminas-eventmanager": "3.3.0",
        "microsoft/azure-storage-common": "1.5.0",
        "microsoft/azure-storage-blob": "1.5.1",
        "paragonie/random_compat": "9.99.100",
        "paragonie/constant_time_encoding": "2.4.0",
        "sabre/vobject": "4.3.3",
        "sabre/dav": "4.1.3",
        "sabre/http": "5.1.3",
        "sabre/uri": "2.2.2",
        "symfony/deprecation-contracts": "v2.5.1",
        "symfony/options-resolver": "v5.4.3",
        "symfony/string": "v5.4.9",
        "symfony/polyfill-mbstring": "1.12.0",
        "smalot/pdfparser": "0.14.0",
        "symfony/debug": "3.4.32",
        "greenlion/php-sql-parser": "4.3",
        "monolog/monolog": "2.2.0",
        "automattic/woocommerce": "3.0.0",
        "zendesk/zendesk_api_client_php": "2.2.11",
        "starkbank/ecdsa": "0.0.5",
	"sendgrid/php-http-client": "3.14.0",
	"sendgrid/sendgrid": "7.9.2",
	"stripe/stripe-php": "7.97",
        "geocoder-php/google-maps-provider": "4.6",
        "geocoder-php/common-http": "4.4",
        "geocoder-php/pelias-provider": "1.3",
        "geocoder-php/here-provider": "0.6.0",
        "geocoder-php/mapbox-provider": "1.3",
        "geocoder-php/nominatim-provider": "5.5.1",
        "geocoder-php/openrouteservice-provider": "1.2",
        "willdurand/geocoder": "4.5.0",
        "php-http/guzzle6-adapter": "2.0.2",
        "php-http/discovery": "1.14.2",
        "php-http/curl-client": "2.2",
        "mautic/api-library": "3.0",
        "vaites/php-apache-tika": "1.2.4",
        "smi2/phpclickhouse": "1.4.4",
        "fzaninotto/faker": "1.9.2",
        "stefangabos/zebra_session": "3.1.0",
        "hi-folks/statistics": "0.2.1"
    }
}

**Comment by Netmees** [comment]
with thi other configuartion in other old installationa there its no problem

{
    "require": {
        "symfony/console": "3.4.32",
        "twilio/sdk": "5.37.0",
        "tecnickcom/tcpdf": "6.3.2",
        "knplabs/gaufrette": "0.9.0",
        "gaufrette/azure-blob-storage-adapter": "0.6.0",
        "gaufrette/ftp-adapter": "0.4.0",
        "guzzlehttp/psr7": "1.6.1",
        "guzzlehttp/promises": "1.3.1",
        "guzzlehttp/guzzle": "6.4.1",
        "onelogin/php-saml": "3.4.1",
        "laminas/laminas-cache": "2.10.0",
        "laminas/laminas-json": "3.1.2",
        "laminas/laminas-serializer": "2.9.1",
        "phpseclib/phpseclib": "2.0.31",
        "psr/log": "1.1.1",
        "firebase/php-jwt": "5.0.0",
        "google/auth": "1.6.0",
        "google/apiclient-services": "0.120",
        "google/apiclient": "2.4.0",
        "laminas/laminas-zendframework-bridge": "1.1.1",
        "laminas/laminas-stdlib": "3.3.1",
        "psr/container": "1.0.0",
        "laminas/laminas-servicemanager": "3.5.1",
        "laminas/laminas-eventmanager": "3.3.0",
        "microsoft/azure-storage-common": "1.5.0",
        "microsoft/azure-storage-blob": "1.5.1",
        "paragonie/random_compat": "9.99.100",
        "paragonie/constant_time_encoding": "2.4.0",
        "sabre/vobject": "4.3.3",
        "sabre/dav": "4.1.3",
        "symfony/polyfill-mbstring": "1.12.0",
        "smalot/pdfparser": "0.14.0",
        "symfony/debug": "3.4.32",
        "greenlion/php-sql-parser": "4.3",
        "monolog/monolog": "2.2.0",
        "automattic/woocommerce": "3.0.0",
        "zendesk/zendesk_api_client_php": "2.2.11",
        "starkbank/ecdsa": "0.0.5",
	"sendgrid/php-http-client": "3.14.0",
	"sendgrid/sendgrid": "7.9.2",
	"stripe/stripe-php": "7.97",
        "geocoder-php/google-maps-provider": "4.6",
        "php-http/guzzle6-adapter": "2.0.2",
        "geocoder-php/here-provider": "0.6.0",
        "geocoder-php/mapbox-provider": "1.3",
        "geocoder-php/nominatim-provider": "5.5.1",
        "geocoder-php/openrouteservice-provider": "1.2",
        "php-http/curl-client": "2.2"
    }
}

**Comment by joebordes** [comment]
php version?
try deactivating error_reporting and display_errors. if that works, turn it on again and look in the console for some PHP warning message in some network call (or look in the apache error.log) and share the warning with me

**Comment by Netmees** [comment]
php 7.4 try to git submodule update vendor to reproduce on demo

**Comment by joebordes** [comment]
we don't use submodules for anything, so either it is some of your own submodules or not necessary at all

**Comment by Netmees** [comment]
i thought that submodules upgrades the vendor folder...

**Comment by joebordes** [comment]
no, it doesn't that is composer.
you don't need to upgrade vendors, we do that for you, just pull

**Comment by Netmees** [comment]
ahh ok... the git pull upgrades the wendor needed...
so perhaps the git submodule update its generating the issue.... i will show the errors to find out where its the problem

**Comment by Netmees** [comment]
i had discover that enabling tracy debugger was the problem
maybe in the configuration of tracy i have to insert crsf values to don´t interrupt some scripts on corebos...
i am trying to make a developing framework with nette tools and corebos... any advise @joebordes ?

**Comment by joebordes** [comment]
glad you got it working!
looks like a nice enhancement.  Have fun!!
