### ISSUE TITLE
Quote Email PDF not work after last update coreBOS 8.0  (baf8d5c8420230209)

### ISSUE THREAD

**Issue by lorenzogreco** [tsolucio/corebos#1501]
In Quote module,  select Email Pdf, (priviosly created with gendoc)
The email popup not automatically fit the TO: field with the contacts email

regards
Lorenzo

coreBOS 8.0  (baf8d5c8420230209)

**Comment by joebordes** [comment]
I just tried and it worked. I am clicking on the "Send PDF" link under the GenDoc widget, right?

**Comment by lorenzogreco** [comment]
Yes, and tryng better works  with old quotes but i can't undestand why doesn't work with the last contact

**Comment by lorenzogreco** [comment]
found the mistake
the contact's field Email Opt Out  was flagged
now it works
