### ISSUE TITLE
Disable Sendgrid detailview email fields by adding global variable... set default disabled #enhancement

### ISSUE THREAD

**Issue by Netmees** [tsolucio/corebos#1521]
the fields of sendgrid are default on CRM even if SendGrid its not setup

i have disabled them manualy on modules/Emails/Emails.php

    public $list_fields = array(
        'Subject' => array('activity' => 'subject'),
        'Related to' => array('seactivityrel' => 'parent_id'),
        'Date Sent' => array('activity' => 'date_start'),
        'Time Sent' => array('activity' => 'time_start'),
        'Assigned To' => array('crmentity' => 'smownerid'),
        //'Delivered' => array('emaildetails' => 'delivered'),
        'Open' => array('emaildetails' => 'open'),
        //'Clicked' => array('emaildetails' => 'clicked'),
        //'Bounce' => array('emaildetails' => 'bounce'),
        //'Unsubscribe' => array('emaildetails' => 'unsubscribe'),
        'Access Count' => array('email_track' => 'access_count')

i think this must be disabled by default and enabled over global variable or when sengrid module its setup

**Comment by joebordes** [comment]
can't you do that with a listview business map?

**Comment by Netmees** [comment]
i imagine i can do it.... that's what i thougt at first... but the point it's that those fields must only be visible if the sendgrid configuration its setup and running... if someone installs the system and setup normas smtp configuration... and its waiting to have this information becouse the fields are there...

**Comment by joebordes** [comment]
I understand. will add to our to-do list
thanks

**Comment by Netmees** [comment]
thanks @joebordes have a nice day :+1:
