### ISSUE TITLE
Send Individual Emails not works in Campaing

### ISSUE THREAD

**Issue by lorenzogreco** [tsolucio/corebos#1551]
![image](https://user-images.githubusercontent.com/19155538/228893403-82b7d815-e6d7-4fd7-8ea9-e6d26c689d55.png)

Hi all,
sending email from campaign module to all contact,  with "Send Individual Emails" flagged not works.
The module send only an email with all contact in TO: Field, 
Also the Email popoup results locked in the windows, impossible to moove left right up down.

coreBOS 8.0  (684027d9520230324)
regards
Lorenzo

**Comment by joebordes** [comment]
thanks
