### ISSUE TITLE
Campaign -> Contact Status not work

### ISSUE THREAD

**Issue by lorenzogreco** [tsolucio/corebos#1554]
Contac'ts status in campaign doesn't work.
You can not change the status for each contact ( --none, contacted successful ecc ecc)

version 32c52415420230331
regards
Lorenzo

**Comment by joebordes** [comment]
please pull and try. let me know
should be fixed with c2095d6c40c739604e643a28ae9e2694d982337b

**Comment by lorenzogreco** [comment]
Now it works
regards
Lorenzo
