### ISSUE TITLE
popup list lookup

### ISSUE THREAD

**Issue by rtougn** [tsolucio/corebos#1565]
![loi](https://github.com/tsolucio/corebos/assets/45679124/e9e55a06-a68c-4164-9d70-12e0b22e3167)

Help me. I installed
successful but all list lookups are not displayed

**Comment by joebordes** [comment]
Hi

Is that in Windows? If so, please try this:

https://corebos.com/docs_grav/getting-started/installation

and let me know.

**Comment by rtougn** [comment]
;include_path = \xampp\php\PEAR
include_path = ".;D:\xampp\php\PEAR"

due to this error. I fixed it. Thanks a lot
