### ISSUE TITLE
xampp 7.4 on windows cann't import module

### ISSUE THREAD

**Issue by rtougn** [tsolucio/corebos#1566]
I generated a module but i can't import it.
I import the downloaded zip file. I use xampp 7.4 on windows.

![image](https://github.com/tsolucio/corebos/assets/45679124/f1793472-e063-40b0-ac7a-9db857e1ff55)
![image](https://github.com/tsolucio/corebos/assets/45679124/01a2a2db-55ea-46f5-a948-61744c7bce25)

**Comment by joebordes** [comment]
share the .zip file with us, please

**Comment by rtougn** [comment]
[Color.zip](https://github.com/tsolucio/corebos/files/14773694/Color.zip)
it here, tks

**Comment by joebordes** [comment]
did you .zip that file yourself or download it from the application?

**Comment by joebordes** [comment]
it looks ok. going to give it a try

**Comment by rtougn** [comment]
I tried another file on the internet and it was ok, but the file I created doesn't work

**Comment by denaldhushi** [comment]
@joebordes I think the problem is to the zip. the zip is not generated with the correct file structure.
directories are missing, they are generated as files `modules/test/test.php`.
It can be an issue with ziparchive extension I guess?
![image](https://github.com/tsolucio/corebos/assets/20266205/a8090ee6-ab6a-47b7-b3fe-fe53c3f8101d)

**Comment by joebordes** [comment]
yes @denaldhushi, you are right! the directory structure is separated by a backslash (\), not a forward slash (/)
some Windows thing for sure
@rtougn please try to use another zip tool, something compatible with the UNIX format and let us know
the files seem to be correct from what I see

**Comment by rtougn** [comment]
I don't quite understand. error appears when creating .zip file? I tried uninstalling winrar -> 7zip but still error

**Comment by joebordes** [comment]
https://superuser.com/questions/1382839/zip-files-expand-with-backslashes-on-linux-no-subdirectories

HTH

**Comment by joebordes** [comment]
let us know how it goes and what you have to configure to get the right format

**Comment by joebordes** [comment]
I just connected to a windows machine, created directory structure, selected the files, right clicked and selected "compress zip". downloaded the file to my linux server and it has the forward slash correct. try that

```shell
$ unzip -l /home/joe/test.zip 
Archive:  /home/joe/test.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2024-03-27 18:15   New folder/New Text Document.txt
        0  2024-03-27 18:15   New Text Document.txt
---------                     -------
        0                     2 files
```

**Comment by joebordes** [comment]
I hope you found a solution. If so, and you can, share :-)
