### ISSUE TITLE
Webservices Warning: Invalid argument supplied for foreach() in Campaigns.php on line 427

### ISSUE THREAD

**Issue by reetp** [tsolucio/corebos#157]
I was trying to run the a webservice query and kept getting an error.
I was trying to get Contacts related to a Campaign.

```
    $docID = '17x130433'; // Campaign
    $module = "Campaigns";
    $relModule = "Contacts";
    $queryParameters = array (
      'limit'=> '3',
      'offset'=>'0'//,
      //'orderby'=> ''
    );
        $params = array(
            "sessionName" => $this->token,
            "operation" => "getRelatedRecords",
            "id" => $docID,
            "module" => $module,
            "relatedModule" => $relModule,
            "queryParameters" => json_encode($queryParameters)
        );
```
Here was the error:

( ! ) Warning: Invalid argument supplied for foreach() in /home/e-smith/files/ibays/testbay/html/corebos/modules/Campaigns/Campaigns.php on line 427
--

1 | 0.0010 | 767544 | {main}(  ) | ../webservice.php:0
2 | 0.3448 | 43563728 | OperationManager->runOperation(  ) | ../webservice.php:172
3 | 0.3448 | 43564568 | call_user_func_array:{include/Webservices/OperationManager.php:138} (  ) | ../OperationManager.php:138
4 | 0.3448 | 43565328 | getRelatedRecords(  ) | ../OperationManager.php:138
5 | 0.3634 | 43955608 | __getRLQuery(  ) | ../GetRelatedRecords.php:75
6 | 0.5029 | 45762120 | call_user_func_array:{/home/e-smith/files/ibays/testbay/html/corebos/include/Webservices/GetRelatedRecords.php:293} (  ) | ../GetRelatedRecords.php:293
7 | 0.5029 | 45762640 | Campaigns->get_contacts(  ) | ../GetRelatedRecords.php:293
8 | 0.5505 | 45849000 | Campaigns->add_status_popup(  ) | ../Campaigns.php:300

Seems that the Campaigns.php expects $related_list['entries'] to be set, which it isn't if this is a WS query.

I did the following hack which works, but could probably be dealt with a lot better :-)

```
--- a/modules/Campaigns/Campaigns.php
+++ b/modules/Campaigns/Campaigns.php
@@ -424,17 +424,22 @@ class Campaigns extends CRMEntity {
 				$this->campaignrelstatus[$row['campaignrelstatus']] = $r;
 			}
 		}
-		foreach($related_list['entries'] as $key => &$entry)
-		{
-			$popupitemshtml = '';
-			foreach($this->campaignrelstatus as $campaingrelstatus)
-			{
-				$camprelstatus = $campaingrelstatus['campaignrelstatusi18n'];
-				$popupitemshtml .= "<a onmouseover=\"javascript: showBlock('campaignstatus_popup_$key')\" href=\"javascript:updateCampaignRelationStatus('$related_module', '".$this->id."', '$key', '".$campaingrelstatus['campaignrelstatusid']."', '".addslashes($camprelstatus)."');\">$camprelstatus</a><br />";
-			}
-			$popuphtml = '<div onmouseover="javascript:clearTimeout(statusPopupTimer);" onmouseout="javascript:closeStatusPopup(\'campaignstatus_popup_'.$key.'\');" style="margin-top: -14px; width: 200px;" id="campaignstatus_popup_'.$key.'" class="calAction"><div style="background-color: #FFFFFF; padding: 8px;">'.$popupitemshtml.'</div></div>';
-
-			$entry[$status_column] = "<a href=\"javascript: showBlock('campaignstatus_popup_$key');\">[+]</a> <span id='campaignstatus_$key'>".$entry[$status_column]."</span>".$popuphtml;
+	
+		if (isset($related_list['entries'])) {
+			
+				foreach($related_list['entries'] as $key => &$entry)
+				{
+					$popupitemshtml = '';
+					foreach($this->campaignrelstatus as $campaingrelstatus)
+					{
+						$camprelstatus = $campaingrelstatus['campaignrelstatusi18n'];
+						$popupitemshtml .= "<a onmouseover=\"javascript: showBlock('campaignstatus_popup_$key')\" href=\"javascript:updateCampaignRelationStatus('$related_module', '".$this->id."', '$key', '".$campaingrelstatus['campaignrelstatusid']."', '".addslashes($camprelstatus)."');\">$camprelstatus</a><br />";
+					}
+					$popuphtml = '<div onmouseover="javascript:clearTimeout(statusPopupTimer);" onmouseout="javascript:closeStatusPopup(\'campaignstatus_popup_'.$key.'\');" style="margin-top: -14px; width: 200px;" id="campaignstatus_popup_'.$key.'" class="calAction"><div style="background-color: #FFFFFF; padding: 8px;">'.$popupitemshtml.'</div></div>';
+		
+					$entry[$status_column] = "<a href=\"javascript: showBlock('campaignstatus_popup_$key');\">[+]</a> <span id='campaignstatus_$key'>".$entry[$status_column]."</span>".$popuphtml;
+				}
+				
 		}
 		return $related_list;
 	}
```
I haven't tested other combinations yet but am wondering if similar issues exist elsewhere.

**Comment by joebordes** [comment]
Looks like you are using coreBOS Webservice Development Tool.  Nice!! :-)

I did a few more tests with accounts and leads, so I added a few more conditions to eliminate some other warnings.

Note that I have been on a personal crusade to eliminate all warnings in the application. A year ago it wasn't even possible to run the application in E_ALL, so any of these that you run into, send them to me, as I almost have them all :-)

This is a particular case because Campaigns has that totally non-standard status picklist on the related list for each entry, so I don't think we will have this issue anywhere else.

Thanks !!

**Comment by reetp** [comment]
Well, I am using the coreBOS webservices code in a roundabout fashion at the minute to solve an urgent issue :-) All a bit of a hack of a hack..... using a coreBOS install to use the webservices to do stuff I can't with vTiger :-) I'm not using the full test suite as yet. 

If I find anything else I'll post back - there are loads of typos and stuff but nothing else serious. I will try and send some sample query stuff I have built up to add to your docs.

No worries Joe - you know I'll always help where and when I can.

Now I just have to figure how to retrieve and add Product attachments...... if that is actually possible?

**Comment by joebordes** [comment]
There is no support for the multiimage field on products but you can add as many image fields as you want and upload those via webservice

https://youtu.be/vgbrz092VDE

You will find a few examples of that in the coreBOS Webservice Development tool:

https://github.com/tsolucio/coreBOSwsDevelopment/blob/master/testcode/438_createWithImage.php

https://github.com/tsolucio/coreBOSwsDevelopment/blob/master/testcode/438_updateWithImage.php

Please do send the queries, that is always helpful.
