### ISSUE TITLE
webservices/Update.php attachments issue

### ISSUE THREAD

**Issue by reetp** [tsolucio/corebos#159]
Ok, may be it is me, and maybe not :-)

I am trying to add an Image to a Product but I think there may be an issue with the array handling in Update.php

here's the code:

```
	if (!empty($element['attachments'])) {
		foreach ($element['attachments'] as $fieldname => $attachment) {
			$filepath = $root_directory.'storage/'.$attachment['name'];
			file_put_contents($filepath, base64_decode($attachment['content']));
			$_FILES[$fieldname] = array(
				'name' => $attachment['name'],
				'type' => $attachment['type'],
				'tmp_name' => $filepath,
				'error' => 0,
				'size' => $attachment['size']
			);
		}
```
I realised this should theoretically handle multiple attachments.

I have an array as follows (see he screenshot):

$element
  => attachments
   ==> content
   ==> name
   ==> size
   ==> type

First issue is the $filepath... $attachment['name] shows the correct filename but I actually end up with a path like this:

....corebos/storage/i

So the $filepath seems not quite right somehow.

file_put_contents then fails. 

Second I would have expected it to have been something like:

.....corebos/storage/2017/August/weekx/123456_image001.jpg ??(where 123456 is the id)

![attachments1](https://user-images.githubusercontent.com/3800384/29488133-cba50972-8504-11e7-89b7-571cab5d2bd7.png)

**Comment by joebordes** [comment]
First, this code you are looking at is for normal image fields. In other words, you create various image fields on a module (uitype 69), each is an individual image field with its own name. You can then upload images to any of those fields with the array structure you are looking at.

The special multi-image field on products (uitype 69m) is **NOT** supported by webservice.

The 
```
$filepath = $root_directory.'storage/'.$attachment['name'];
```
is a cache, temporary upload, which, in fact, has been moved to the cache directory:

https://github.com/tsolucio/corebos/blob/master/include/Webservices/Update.php#L39

the "save" process will copy them from this temporary cache to the definite storage directory.

HTH

**Comment by reetp** [comment]
Oh bother.........

Is it possible to create just the link with webservices (on the basis I could copy image files across manually) ?

I can retrive the image link info ok with webservices.

**Comment by joebordes** [comment]
I understand that you want to upload a set of images to the mulit-image field in your products.

We added to coreBOS a mass upload feature a few years ago:

https://youtu.be/usWQDoCVw_w

I had a look at that and it uses a service end point we added specifically for that use:

https://github.com/tsolucio/corebos/blob/master/modules/Products/UploadImage.php

Looking at that code, I thought it should be relatively easy to create a script to accomplish what you are looking for, so I created this HelperScript:

https://github.com/tsolucio/corebos/blob/master/build/HelperScripts/productmassimageupload.php

You should be able to copy that to the top of your vtiger CRM, change the productID variable to one that you have in your system and execute the script to get the two indicated images imported. It worked for me.

Once you have that, it is an exercise of constructing some array with product CRMIDs and the location of the images for each.

Let me know how it goes.

**Comment by reetp** [comment]
Ha - both burning the midnight oil then :-)
I actually only need one product image, though the option of more is even better !!
That's awesome Joe - I'll test ASAP.

**Comment by reetp** [comment]
Is it possible to call it as a remote webservice, or can you only use it on the actual server ?

**Comment by joebordes** [comment]
I created the script for it to be launched from the actual server and from inside the root of the application. I don't think it would be difficult to convert it into a Webservice call as the functionality is already in place.

Making it a Webservice call is basically:
 - create a file in include/webservice
 - create a function with a similar interface as the other methods and put the above code inside
 - add the same protections that other webservice methods have for security
 - adapt the code to the webservice format of IDs and base_decode according to the input parameters
 - register it using the build/wsChanges format
 - create a test script in coreBOS Webservice development tool to prove it is working

There is always a big difference between "making it work" and "making it work for everyone" :-)

I will help all I can....

**Comment by reetp** [comment]
Okee dokee..... I figured most of the bits were probably there. It's just making it all work.
Not sure I can do all that myself but I'll have a go and see what happens !
Reason for this is we have a huge pile of products but don't want to import them into vTiger all in one go - pointless having 10,000+ products when you will probably only use a couple of hundred. 
We want a local 'page' we can select new Products that are stored on our local server and add them or update them to them remote instance as we want.

**Comment by reetp** [comment]
OK, so I added a service 
```
 $operationInfo = array(
	'name'    => 'addProductImages',
	'include' => 'include/Webservices/UploadProductImages.php',
	'handler' => 'cbws_uploadProductImages',
	'prelogin'=> 0,
	'type'    => 'POST',
	'parameters' => array(
		array('name' => 'id','type' => 'String')
	)
);
```

When I debug I get to webservices line 172

		$rawOutput = $operationManager->runOperation($operationInput,$current_user);

$operationInput = 6x41838 (the WS product ID)

This gets to function runOperation in OperationManager, but it only carries the Product ID, and no other parameters.

I correctly end up at my new WS file UploadProductImages.php but the only way I can see to access the parameters is via the $_POST parameters at this point.

Is this correct or should they have been picked up and passed on earlier ? 

I can see that I can see we get
 		$input = $operationManager->getOperationInput();

Which has the array data.

But further down we then do (as noted above):

		$operationInput = $operationManager->sanitizeOperation($input);

Which leaves us with just the ID. So when runOperation is called it leaves the $input data array behind ?

I know I could extract the data from the post request in my new file, and sanitise the data but if I look at say Create.php it has the create function like this which is what I would have expected ?

function vtws_create($elementType, $element, $user) {

Suggestions appreciated - I'm a noob at this !

**Comment by joebordes** [comment]
I think you are oversomplicating it, you just have to create the cbws_uploadProductImages function in include/Webservices/UploadProductImages.php

you are missing the file parameter

```
$operationInfo = array(
	'name'    => 'addProductImages',
	'include' => 'include/Webservices/UploadProductImages.php',
	'handler' => 'cbws_uploadProductImages',
	'prelogin'=> 0,
	'type'    => 'POST',
	'parameters' => array(
		array('name' => 'id','type' => 'String'),
		array('files' => 'id','type' => 'encoded'),
	)
);
```

that second parameter will permit you to send an array of files, something like:

```
$files = array(
'file1'=>base64_encode('your image1'),
...
```

Now, in the function, you loop over the array, decode the file and save it in the cache directory, call the code I shared above and delete the image.

Keep asking....

**Comment by reetp** [comment]
Doh.... call me stoopid, but I cannot seem to get the POST array format right. I've tried a myriad of combinations but cannot seem to get the element data into the UploadProductImages.php file so I can pass the array.

Create /include/webservices/UploadProductImages.php containing:

function cbws_uploadProductImages($element, $user)
{
// Some code to check what parameters we have been given in $element
// $user is OK, but only seem to get the Product ID in $element
}

Create WS file as above and register it with InstallRESTChanges.php

Run webserviceDemoAddProductImage.php

In webservice.php I get the following (not necessarily quite right, but anyway....)

$input => 
element { id:filename,file1:{base64endodefile} }
elementType: Products
id=6x41838 (the product ID)
operation: addProductImages
sessionName: 123456789abcdefg

Once that goes through 

		$operationInput = $operationManager->sanitizeOperation($input);

I just get 

$operationManager => id = 6x41838

That goes to runOperation, and is then sent via call_user_function_array as $parameter.

I can see in other operations like Create there are other elements that should be in this array but I can't understand why mine are not getting passed over in the sanitise data operation. One of those thing where when you know, you know....

Patience appreciated!

**Comment by joebordes** [comment]
You have to be REALLY close. make a PR, I'll accept it as it is and finish the method for you. No problem.

**Comment by reetp** [comment]
Yeah I know :-)

That's the frustrating part is I'm stuck in an early section, not the later bit ! I know if I can figure why the parameters aren't being passed, I can do quite a bit more without problems.

Anyway, it's just code. I'll figure it eventually I guess.

**Comment by reetp** [comment]
Ahhhhh..... so easy... when you know how :-)

For future reference you need to make sure your elements get properly registered in vtiger_ws_operation_parameters.

Not sure why mine won't register correctly with InstallRESTCHanges.php but I'll figure that eventually !

OK, now I need to try and make it start to work......

**Comment by reetp** [comment]
Ok, next clue required...

I have my shiny image names/data in my funky new file.

Yes, I can decode the base64 data.

How does vtiger insert the files into the storage/year/week format ?

Is there a function or do you just have to calculate it manually?

Does the file need extracting to a temp location first ?

**Comment by joebordes** [comment]
the files need extracting to a temp location first

Following the initial import image script I made, that expects to have the images already present in the application structure, loop over your file parameter and decode the images into the cache directory, then apply the same technique I used to get them loaded into the application.

finally, delete them from cache

**Comment by reetp** [comment]
Yup, I figured it earlier. I can insert one or more now :-)

It's currently ugly, but basically works.

One issue I note is there seems to be no way to check if insertIntoAtttachment succeeds or fails ? Neither function in Products or CRMEntity has a return value which I find a little odd !

One other point - viger shows a max of 6 files for insertion.

From my webservice file, how can I get to the function cbws_getrecordimageinfo($id, $user) which I could use to check ? Or do you have to write another function inside this?

I've tried using a require_once for the WS file but that throws insufficient permissions errors

**Comment by joebordes** [comment]
You should be able to load the getRecordImages script with no problem. Can you paste the exact error?

You could use the query on line 78 modified to return the count as all you need is the number of images already loaded.

In any case, I think that it will work the same, even if you upload 10 pictures it will show them all. In fact, in coreBOS this number is a configurable value with a global variable so I wouldn't worry too much about that.

**Comment by reetp** [comment]
It runs the function but we get a Permsission Denied presumably for the user or model. I'll add a couple of file here to look at shortly.

**Comment by kapsule** [comment]
@reet. This error is caused by a user access problem that has been logged in the webservice. You probably do not have access to that field. If you do it from the web does it work? Logically you must use the same webservice user. 

_Sent from my HUAWEI MHA-L09 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by reetp** [comment]
@kapsule I am sure you are right. Got something wrong somewhere whwn I am trying to check access permissions for tge webservice user against Products. Noobs for you :-)

Now it kind of works basically I'll get to do a fork/push/PR tomorrow so you can all have a chuckle !!

_Sent from my Samsung SM-G920F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kapsule** [comment]
@reet. Perfect. If you need help with any test you are counting. If you can have a better fork. So we can perform more real tests.
