### ISSUE TITLE
Optimize screen space reducing whitespace?

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#161]
Can you reduce some of the whitespace in detail view to optimize information?

![optimizewhitespace](https://user-images.githubusercontent.com/1237191/29558739-5e724948-872d-11e7-8832-b28ef4ba5bde.png)

![optimizewhitespace2](https://user-images.githubusercontent.com/1237191/29558740-5e73a450-872d-11e7-8ea2-c7b93ff539e2.png)

**Comment by ekane95** [comment]
Yes i was thinking of reducing that space on list view..but on detail view i thought it was better with that space to get a more understanding look of the blocks

**Comment by ekane95** [comment]
I fixed the spaces on list view

**Comment by joebordes** [comment]
Looks much better to me that way. Thanks!

Here is another one

![morewhitespace](https://user-images.githubusercontent.com/1237191/29572496-cd7dc8e2-875c-11e7-84df-a9ee9ebdc088.png)

**Comment by ekane95** [comment]
Fixed this
