### ISSUE TITLE
Search broken

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#163]
![searchbroken](https://user-images.githubusercontent.com/1237191/29572590-0cebca1a-875d-11e7-8a96-e5c84005a426.png)

**Comment by ekane95** [comment]
Strange, on localhost works

**Comment by ekane95** [comment]
This is the error on online demo:

Fatal error: Uncaught WebServiceException: Permission to perform the operation is denied in /var/www/coreboslds/include/Webservices/Retrieve.php:38 Stack trace: #0 /var/www/coreboslds/modules/com_vtiger_workflow/VTEntityCache.inc(24): vtws_retrieve('29x4062', Object(Users)) #1 /var/www/coreboslds/modules/com_vtiger_workflow/VTEntityCache.inc(116): VTWorkflowEntity->__construct(Object(Users), '29x4062', false) #2 /var/www/coreboslds/modules/com_vtiger_workflow/VTWorkflowManager.inc(184): VTEntityCache->forId('29x4062') #3 /var/www/coreboslds/modules/com_vtiger_workflow/VTWorkflowManager.inc(166): VTWorkflowManager->getoneRACWorkflowForRecord('Assets', '29x4062') #4 /var/www/coreboslds/include/utils/ListViewUtils.php(946): VTWorkflowManager->getRACRuleForRecord('Assets', '29x4062') #5 /var/www/coreboslds/modules/Home/UnifiedSearch.php(178): getListViewEntries(Object(Assets), 'Assets', Object(ADORecordSet_mysqli), Array, '', '', '', '', Object(CustomView)) #6 /var/www/coreboslds/index.php(545): include_once('/var/www/corebo. in /var/www/coreboslds/include/Webservices/Retrieve.php on line 38

**Comment by joebordes** [comment]
Fixed: tabdata.php file was not up to date
