### ISSUE TITLE
Reduced global search: click outside results to hide them

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#165]
![globalautosearchclose](https://user-images.githubusercontent.com/1237191/29579914-8dcbf1ac-8774-11e7-85a5-da6d84552d43.png)

**Comment by AlbanaCelepija** [comment]
I just committed the change to hide the results when clicking outside.Also tested the existing ui 10 with autocomplete and added condition to show the list of results when there is one map for them also.

**Comment by joebordes** [comment]
works correctly. thanks!
