### ISSUE TITLE
Submenu items jump on hover and lack vertical padding

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#166]
The LDS submenu seems to have changed (maybe because of the new LDS?) I created the Smarty, so if you need any help, let me know.
![corebos-lds-menu](https://user-images.githubusercontent.com/8875222/29615292-a3c84e8a-880d-11e7-99db-d2dd69244ef1.jpg)

**Comment by joebordes** [comment]
@ekane95 remember to update your branch because I made some changes to the menu a few days ago
