### ISSUE TITLE
Detail view block headers are incorrect

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#168]
They are all the same "Comments"

![screen shot 2017-08-24 at 10 10 35](https://user-images.githubusercontent.com/1237191/29670476-08515b74-88e7-11e7-9411-83f167dc54e3.png)

**Comment by joebordes** [comment]
What did you do to close this?
You should put the issue number in the commit message so it gets related automatically

**Comment by ekane95** [comment]
Sorry I closed it because i fixed it

2017-08-29 11:04 GMT+02:00 Joe Bordes <notifications@github.com>:
