### ISSUE TITLE
Mobile login page boxes need some margin

### ISSUE THREAD

**Issue by reetp** [tsolucio/corebos#175]
Just started playing with the Mobile front end and noting stuff as I go.

The Login page has the boxes going right to the edge.

I think a small change to the css like this might help (not sure how this affects it elsewhere so not hacking to much)

theme.css around line 44

ui-field-contain
    margin: 0.5em;

Without:

![mobile1](https://user-images.githubusercontent.com/3800384/30549130-44e6231a-9c94-11e7-9533-6fb35a992fbd.png)

With:
![mobile2](https://user-images.githubusercontent.com/3800384/30549134-46ea731e-9c94-11e7-9023-a2de70564c8c.png)

**Comment by reetp** [comment]
As an addendum to this the password 'Show password box' would be better placed below the password box

**Comment by omarllorens** [comment]
Thanks @reetp .
