### ISSUE TITLE
Mobile webpage does not have logout

### ISSUE THREAD

**Issue by reetp** [tsolucio/corebos#176]
As far as I can see the mobile web page does not have a logout button anywhere?

This should at least be an option ?

**Comment by joebordes** [comment]
Open the side menu and you will see the logout button on the left of the menu bar

![mobilelogout](https://user-images.githubusercontent.com/1237191/30549668-a76f71f2-9c95-11e7-84ee-2ea6f6e72227.png)

it is a little hard to find :-)

**Comment by reetp** [comment]
Ahhhh. My FF mobile 55 (S6, Marshymallow)  slides that top bar all the way to the left and you then don't notice it in the upper left corner.....

Something to think about....  Dolphin is OK

![logout](https://user-images.githubusercontent.com/3800384/30550790-d453137e-9c98-11e7-9cc3-14c6d59bd301.png)
