### ISSUE TITLE
Mobile webpage cannot associate Organisation

### ISSUE THREAD

**Issue by reetp** [tsolucio/corebos#177]
Sure this isn't a biggy but I added a Contact, then an Organisation

I went back to the Contact and tried to link an organisation.

I get the search box, can type in letters, but do not seem to be able to search for anything.

**Comment by omarllorens** [comment]
Hi @reetp , now this search is supported. We had this problem on module Contacts and Accounts. Accounts module have a relation to Accounts too, and is the same that in Contacts.

Please, update when you can.

**Comment by reetp** [comment]
Thanks @omarllorens I'll have a play.
If I ever get 5 minutes we'll get swapped over to CoreBOS !
