### ISSUE TITLE
External report opens direct on view page

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#180]
- create a new report of type "External application"
- type in the URL: http://corebos.org (or any other)
- save the report
- you get directed to the view page which is incorrect, you should be directed to the reports folder page and open the URL in another window/tab
- if you now select another report from the folder (picklist in upper right corner) and then select the external report URL, it opens again in the same view when it should be opening in a new window/tab

**Comment by evolutivo** [comment]
opened pull request : https://github.com/tsolucio/corebos/pull/244

**Comment by joebordes** [comment]
Hi,

The proposed change does not seem to work. It leaves the create report popup screen open with the incorrect listing inside and it does not solve the issue of selecting the report in the listing view.

Can you explain what you are trying to achieve? 

Please follow the steps detailed above to reproduce the issues.

As whatever doubts you may have. Thanks.

**Comment by joebordes** [comment]
PR #246 fixes the creation error for this bug. Now we have pending only the second part:

- if you now select another report from the folder (picklist in the upper right corner) and then select the external report URL, it opens again in the same view when it should be opening in a new window/tab

Thanks!!

**Comment by joebordes** [comment]
fixed second part with #247 

thanks!!
