### ISSUE TITLE
Translate picklist values for searching

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#182]
Use coreBOS translation module to correctly translate picklist values on search

The way picklists are designed is to save the exact picklist value in the database field, this is very nice for searching **IF** we use only one language, but it makes it almost impossible to get right in a multi-language install. In order to get this right, we have created the coreBOS translation module.

**Comment by loridacito** [comment]
Pull request submitted. The translation is based on the cbtranslations module or in the traditional way if there are no records there. Tested with the translations of sales stage (Potentials)
![screenshot from 2018-07-12 12-38-08](https://user-images.githubusercontent.com/9430573/42628509-a0cd5182-85d0-11e8-99dd-e8b642cc8d6d.png)

**Comment by loridacito** [comment]
I also did all the unit tests. In query generator only 3 or 4 failed because the query syntax with the aggregation of the cbtranslation part is different

**Comment by joebordes** [comment]
thanks!!
