### ISSUE TITLE
Check field usage before delete

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#192]
Integrate the checkfieldusage.php script into the Layout Editor in order to show the usage of a field before permitting it to be deleted.

http://blog.corebos.org:8080/en/blog/december2015

**Comment by denaldd** [comment]
i opened a pull request about this 
https://github.com/tsolucio/corebos/pull/236

**Comment by denaldd** [comment]
I made the changes 8d646f53f56e459b3e71e9cdfc416cca98cbadda
