### ISSUE TITLE
Workflow: mass update related modules fields

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#207]
Create task to mass update fields on (many) related records.
For example, update "assigned to" of all contacts on accounts save

**Comment by loridacito** [comment]
-Added a cbupdater for the new wf task
-Added another webservice for getting many to one relations between modules (added statically all the old custom uitype related fields)
-Added task tpl, main class and js file
-Tested with this configuration in an Account workflow:
![screenshot from 2018-02-07 17-23-36](https://user-images.githubusercontent.com/9430573/35927836-faf1e2dc-0c2b-11e8-9a0b-39ded445d28e.png)

Also fixed a format bug when selecting a date to update in the task (in update entity task etc)
