### ISSUE TITLE
calendar.js unreachable code after return statement

### ISSUE THREAD

**Issue by 2038AD** [tsolucio/corebos#209]
I noticed that Firefox complains with Vtiger in the console
![calendarvtiger](https://user-images.githubusercontent.com/29248557/31221229-e4c8cdc8-a9ba-11e7-829a-f081a70dff98.png)

I had a look at the coreBOS demo and it has the same issue (though on a different line it's the same code)
![calendarcorebos](https://user-images.githubusercontent.com/29248557/31221307-21d8a51c-a9bb-11e7-9527-d16c95a49db5.png)

![coreboscode](https://user-images.githubusercontent.com/29248557/31221350-3d8e7bb0-a9bb-11e7-891d-7786df3c8676.png)
It looks like everything after the first return is unreachable.

It looks like it could be that 

	if (!Calendar.is_ie5)
		//	return str.replace(re, function (par) { return s[par] || par; });
		// fix provided by dtnadmin. Many thanks
		for (var i in s) str=str.replace(i, s[i]);
		return str;

isn't closed properly and should be something like 

	if (!Calendar.is_ie5) {
		//	return str.replace(re, function (par) { return s[par] || par; });
		// fix provided by dtnadmin. Many thanks
		for (var i in s) str=str.replace(i, s[i]);
		return str;
	}

Making that change with a test Vtiger install stops FF from complaining. So the diff for coreBOS would be (assuming that's the right fix)

	--- a/jscalendar/calendar.js
	+++ b/jscalendar/calendar.js
	@@ -1693,12 +1693,12 @@ Date.prototype.print = function (str) {
	 	s["%%"] = "%";		// a literal '%' character
	 
	 	var re = /%./g;
	-	if (!Calendar.is_ie5)
	-
	+	if (!Calendar.is_ie5) {
	 		//	return str.replace(re, function (par) { return s[par] || par; });
	 		// fix provided by dtnadmin. Many thanks
	 		for (var i in s) str=str.replace(i, s[i]);
	 		return str;
	+	}
	 
	 	var a = str.match(re);
	 	for (var i = 0; i < a.length; i++) {

thanks :)

**Comment by joebordes** [comment]
That looks absolutely correct to me, but I would take your change a step further. From what I see, the "if" is checking for Internet Explorer 5 which I think we can safely discard as a valid browser now.

So If you can,
 - eliminate the "if (!Calendar.is_ie5)" and all the code below the return which is for IE5 and will never get executed
 - eliminate the "return" comment which is unnecessary
 - indent the for and return correctly
 - create a PR

then I will happily accept it.

Thanks!
