### ISSUE TITLE
Too little whitespace on menu items and table rows

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#221]
https://github.com/tsolucio/corebos/blob/5a8524968b4b6924cc5fe219317d131dc90d8d4d/include/LD/assets/styles/customLD.css#L783

https://github.com/tsolucio/corebos/blob/5a8524968b4b6924cc5fe219317d131dc90d8d4d/include/LD/assets/styles/customLD.css#L787

https://github.com/tsolucio/corebos/blob/5a8524968b4b6924cc5fe219317d131dc90d8d4d/include/LD/assets/styles/customLD.css#L1075

Frankly, I'm not a fan of the narrow setup we used in the LDS override CSS. I believe that if we adopt LDS, we should adopt it as-is mostly. The space we use now is just too narrow for my taste.

**Comment by joebordes** [comment]
Can you make a PR so we can compare?

**Comment by Luke1982** [comment]
Sure, let me try to setup a development local install to test.

**Comment by joebordes** [comment]
closing
