### ISSUE TITLE
Workflow: hide related field picklist when module field is selected

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#230]
- create a workflow with an update field task
- select a uitype10 field, a picklist with the fields of the related module appears
- now, in the same field, select a field that belongs to the module, the picklist of related fields should disappear, but it doesn't

This would be nice to have as it is easy to just delete the whole field and add another one.

related to #206

**Comment by loridacito** [comment]
added commit to solve this issue

**Comment by joebordes** [comment]
this is working. thanks!
