### ISSUE TITLE
Workflow: update field task related field with multiple modules

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#231]
In a workflow update field task, if you select a uitype10 relation field that is related to more than one module, only the fields of the first related module appear.

- create a workflow for potentials and add an update field task
- select the "related to" field. This field is related to Accounts and Contacts but only the fields of the Accounts appear.

We should fill in the picklist with the fields from all related modules and then modify the code to act according to the selected fields.

In the case that the workflow task is set to update a field on a module that is actually not related I would suggest to just ignore that update. For example, if the update field task for the potential says to update the contact first name field, but the potential triggering the workflow is related to an account, that update field should just be ignored.

related to #206

**Comment by loridacito** [comment]
added commit for this fix. Tested with a workflow like this:

![screenshot from 2018-01-26 17-44-19](https://user-images.githubusercontent.com/9430573/35450513-8ee95026-02c0-11e8-9465-608205f4b950.png)

**Comment by joebordes** [comment]
There is an error with the module name being saved. The code is saving the translated value of the module. For example, if you are working in English and select an Account you get:

```
<input type="hidden" id="save_fieldvalues10_1_module" class="type1" value="Organizations">
```

if you are working in Spanish ($deafult_language='es_es') you get:

```
<input type="hidden" id="save_fieldvalues10_1_module" class="type1" value="Cuentas">
```

this gives a fatal error when the task is launched.

Let me know if you need more information

**Comment by loridacito** [comment]
I committed a change fixing the problem

**Comment by loridacito** [comment]
added another commit to solve the multi uitype 10 problem on Accounts

**Comment by joebordes** [comment]
Seems to be working correctly for me also. Even aggregating on "brother" records works!!

Very good job. Thanks!
