### ISSUE TITLE
(getchallenge) Authentication token is updated on every ws call

### ISSUE THREAD

**Issue by albertxhani** [tsolucio/corebos#242]
expiretime is not considered when updating authentication token. That leads to the token being updated every time the WS is called. Having 2 parallel WS calls will result on one call to fail due to login error

**Comment by joebordes** [comment]
I'm not sure I understand the problem. The way the WS interface works is that you call getchallenge and login once. You get a sessionid and use that sessionid for as long as you need it. You only call getchallenge once per session. So it is correct for that method to reset the expire time and session.

Please explain a little bit more. Maybe even some code for the coreBOS WS Development tool to see what you are trying to do and the problem you are having

**Comment by albertxhani** [comment]
Ok in that scenario It works fine. But suppose we have 2 WS calls at the same time and we are not logged in yet. Both WS will require geChallenge to be called and both will update vtiger_ws_userauthtoken with different tokens since expiretime(column in vtiger_ws_userauthtoken) will not play any role on this. This will cause one WS to fail due to a non valid token which it holds. 

This is one solution
`function vtws_getchallenge($username){
	global $adb;

	$authToken = uniqid();
	$servertime = time();
	$new_expire_time = time()+(60*120);

	$user = new Users();
	$userid = $user->retrieve_user_id($username);
	if (empty($userid)) {
		throw new WebServiceException(WebServiceErrorCode::$AUTHREQUIRED,'Given user cannot be found');
	}

	$get_token = $adb->pquery("SELECT * FROM vtiger_ws_userauthtoken WHERE userid = ?", array($userid) );

	if($adb->num_rows($get_token) == 1) {
		$user_data = $adb->fetchByAssoc($get_token, 0);
		$expired_time_unix = $user_data['expiretime'];
		$expiretime = new DateTime("@$expired_time_unix"); 

		$now = new DateTime();
		$diff = $expiretime->diff($now);

		if($diff->invert == 0) {

			$sql = "delete from vtiger_ws_userauthtoken where userid=?";
			$adb->pquery($sql,array($userid));

			$sql = "insert into vtiger_ws_userauthtoken(userid,token,expiretime) values (?,?,?)";
			$adb->pquery($sql,array($userid,$authToken,$new_expire_time));

		} else {
			$authToken = $user_data['token'];
			$new_expire_time = $expired_time_unix;
		}
	} else {
		$sql = "insert into vtiger_ws_userauthtoken(userid,token,expiretime) values (?,?,?)";
		$adb->pquery($sql,array($userid,$authToken,$new_expire_time));	
	}

	return array("token"=>$authToken,"serverTime"=>$servertime,"expireTime"=>$new_expire_time);
}`

**Comment by joebordes** [comment]
Ok, I understand. Your solution seems correct to me. Can you please apply the [coreBOS Standard Formatting](http://corebos.org/documentation/doku.php?id=en:devel:developmentguidelines) and create a PR?

Have a nice weekend
Thanks!!

**Comment by joebordes** [comment]
fixed: fc7ce84171dd9bfe8f60a7b8c4c4c766f95ba2dd

thanks!!
