### ISSUE TITLE
Google Calendar Sync: ”No refresh token”

### ISSUE THREAD

**Issue by partnerwerk** [tsolucio/corebos#249]
Hello TSolucio/CoreBOS team,

after updating CoreBOS recently the GCal sync script loses connection to GCal as soon as I log out from CoreBOS. I manually refreshed the tokens within the Settings in Google's Webdeveloper Console but this did not change the behavior.

So it is possible to connect to GCal, the connection works as long as I am logged in and creating new dates. But when I log out and in again I have to remember to reconnect Cal4You with GCal - which I do not always do :-(

**Comment by evolutivo** [comment]
Hi @partnerwerk ,

I wasn't able to reproduce the problem with the latest version of Corebos crm. I tried it with admin and non admin user. Have you applied also the cbupdater changes along with the code update? What message does the Calendar Settings show. For example mine:
![screenshot from 2018-03-12 10-35-26](https://user-images.githubusercontent.com/7868031/37276142-3c1ad150-25e1-11e8-9f9e-d1a6bbaf474e.png)

You could try to clear the tokens , choose Authorize and Connect again and logout , login.

**Comment by partnerwerk** [comment]
Thank you @evolutivo,

I have got the same settings and the latest update was completed with CoreBOS updater. I did all of your suggestions again but it did not fix it. Also clearing the tokens was no solution.

I could finally solve the problem by creating a new OAuth client in the Google Webdeveloper Console. Now GCal stays connected with logging out and in again.
