### ISSUE TITLE
Query: SELECT id,user_name FROM vtiger_users WHERE user_name IN () failed

### ISSUE THREAD

**Issue by reetp** [tsolucio/corebos#252]
Noticed this while debugging my LDAP connection:

LDAP global variable enabled

Only user is admin user.

Go to the User page

https://10.0.0.158/corebostest/index.php?module=Users&action=index&parenttab=Settings

I get this from the adodb debugging. Sure it isn't serious but it's there.

mysqli): select fieldname,modulename,tablename,entityidfield from vtiger_entityname where modulename = 'Users'  
(mysqli): SELECT id,user_name FROM vtiger_users WHERE user_name IN ('admin')  
(mysqli): SELECT id,user_name FROM vtiger_users WHERE user_name IN ()  
Query: SELECT id,user_name FROM vtiger_users WHERE user_name IN () failed. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
         ADOConnection._Execute(SELECT id,user_name FROM vtiger_users WHERE user_name IN (), false) % line 1229, file: adodb.inc.php
      ADOConnection.Execute(SELECT id,user_name FROM vtiger_users WHERE user_name IN ()) % line  493, file: PearDatabase.php
   PearDatabase.pquery(SELECT id,user_name FROM vtiger_users WHERE user_name IN (), Array[1]) % line   56, file: ListView.php
include_once(/home/e-smith/files/ibays/corebostest/html/modules/Users/ListView.php) % line   13, file: index.php
include_once(/home/e-smith/files/ibays/corebostest/html/modules/Users/index.php) % line  504, file: index.php

**Comment by joebordes** [comment]
thanks!

**Comment by reetp** [comment]
NP :-)
