### ISSUE TITLE
Security - Enumeration of users

### ISSUE THREAD

**Issue by bpabiszczak** [tsolucio/corebos#272]
https://unsecure.blog/en/121-enumeration-of-users-in-popular-crm-systems.html

**Comment by reetp** [comment]
Can someone block this guy from spamming and trying to promote his own business?

He should know better.

**Comment by bpabiszczak** [comment]
![block_user](https://user-images.githubusercontent.com/10197525/40281216-e99aca70-5c5e-11e8-9709-1cc557f8c3ca.gif)

**Comment by joebordes** [comment]
link lost

**Comment by bpabiszczak** [comment]
The problem solved itself? As in Vtiger ;)

**Comment by joebordes** [comment]
No, your blog post doesn't work so I can't reproduce it

**Comment by joebordes** [comment]
closing
