### ISSUE TITLE
Login page suggestion

### ISSUE THREAD

**Issue by 2038AD** [tsolucio/corebos#289]
It might be an idea to prevent the login page from appearing in (Google) search results with the meta tag `<meta name="robots" content="noindex">`
https://support.google.com/webmasters/answer/93710?hl=en&ref_topic=4598466

The robots.txt should prevent indexing but according to [this page](https://support.google.com/webmasters/answer/6062608) 
> You should not use robots.txt as a means to hide your web pages from Google Search results. This is because other pages might point to your page, and your page could get indexed that way, avoiding the robots.txt file

**Comment by joebordes** [comment]
A very good idea. Thank you.

Note: you should never have your corebos installation open to the internet. Add a [basic authentication](https://wiki.apache.org/httpd/PasswordBasicAuth)
