### ISSUE TITLE
Shouldn't this be 'getGlobalSearch' in stead of 'getGloalSearch'?

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#292]
https://github.com/tsolucio/corebos/blob/7c1ff737d8adfdf355c16e74720f682fcd45f05c/include/js/general.js#L5000

**Comment by omarllorens** [comment]
If it is badly written, but it is badly written there and in the file that expects that name, so it is working well.
Anyway, I have corrected it so that it is better understood.

Thanks!

**Comment by Luke1982** [comment]
Ah OK, thanks for the update!
