### ISSUE TITLE
Time comparison does not allow more than 99 hours

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#295]
https://github.com/tsolucio/corebos/blob/c620de19876a07ce3e9e34261fd9b90aa7f6f128/modules/com_vtiger_workflow/VTJsonCondition.inc#L169

Regex should test for 3 digits in the first column, allowing more than 99 hours (999 hours), or maybe even more?

**Comment by joebordes** [comment]
Check the MySQL documentation as there is a limit to these fields

**Comment by joebordes** [comment]
https://stackoverflow.com/questions/39259910/why-is-mysqls-maximum-time-limit-8385959

**Comment by joebordes** [comment]
so, 3 digits should be fine

**Comment by Luke1982** [comment]
So basically the max is either 999:99:99 or 999:99, depending on whether you have a HH:mm:ss or HH:mm format?

**Comment by joebordes** [comment]
perfect!
