### ISSUE TITLE
CSRF false positive on large file upload

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#336]
If you try import a big file, system show coreBOS Security error, instead a message file bigger than allowed.

For me, if file has more than 40mb, occurs this error 

https://discussions.corebos.org/showthread.php?tid=1204

**Comment by juanSistemas2503** [comment]
Good day.
Are there any updates or solutions regarding this error??

**Comment by joebordes** [comment]
Hi
Every time I tried to reproduce this it was a PHP limitation problem or a limit in the coreBOS upload variable. I could not determine a direct relation between CSRF and the size of the file.

It gives the CSRF error because the ajax call fails, but it is not a representation of the real error.

Can you make sure your PHP settings are correct?

**Comment by joebordes** [comment]
I received another complaint about this today. It seems it only happens with import so I added an exclusion of CSRF for that process. Hope that eliminates this issue although I can't be sure.

**Comment by joebordes** [comment]
I ran into this issue again today while trying to import an 84k rows file of 30Mb

The error message was about insufficient input_variable size and CSRF error on screen but the issue was actually with the post_max_size limit in php.ini. This variable was set to 8Mb. The max_upload_size was 32Mb. Changing post_max_size to 32Mb permitted me to upload the file and import the data.
