### ISSUE TITLE
Why this extra array assignment?

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#449]
https://github.com/tsolucio/corebos/blob/75c3acfc6600910554911bc772f747b6e7698d8e/data/CRMEntity.php#L94

It seems like it is only used in the loop right after it, but why the assignment, couldn't we just loop over the source array directly?

**Comment by joebordes** [comment]
absolutely!  Nice catch.  Do you want to make a PR or should I just fix it?

**Comment by joebordes** [comment]
fixed [here](https://github.com/tsolucio/corebos/commit/aebc68e50155489d7201483672679455efb49680)

thanks!
