### ISSUE TITLE
Products with multiple currencies don't fill costprice in PO's

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#473]
https://github.com/tsolucio/corebos/blob/b780d815f6bb00c62783011ee9dab714d1958863/include/js/Inventory.js#L1869

This lines needs another check for the gVTModule not being PurchaseOrder

**Comment by joebordes** [comment]
Can you explain that a bit more, please?
Multicurrency is not supported on PO, or are we supposed to be retrieving the cost price?

**Comment by Luke1982** [comment]
Woops, missed your comment. Well it's not supported but the JS function that grabs the price doesn't care about it being not supported. It will skip the 'if' that will lead to costprice selection when multicurrency is enabled even when you are in a PO
