### ISSUE TITLE
Faster Reports

### ISSUE THREAD

**Issue by playmono** [tsolucio/corebos#48]
Hi,

I accomplished to make SalesOrder Report faster. From "500 Error" to 10 sec of query and just with this statement in database:

  ALTER TABLE `vtiger_invoice_recurring_info` ADD PRIMARY KEY (salesorderid);

I dont know where you create database, so I made an Issue, hope you dont mind :)

**Comment by joebordes** [comment]
Hi,

We already have this optimization in the code:

https://github.com/tsolucio/corebos/blob/master/build/changeSets/cleanoptimizedatabase_140.php#L92

Please apply all corebos updater changes.
