### ISSUE TITLE
Global Search autocomplete long values bleed out of box

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#491]
![reallylongname](https://user-images.githubusercontent.com/1237191/53752021-ebedb800-3ead-11e9-8790-dc5c61960b11.png)

**Comment by Luke1982** [comment]
![schermafdruk van 2019-03-07 21-32-27](https://user-images.githubusercontent.com/8875222/53987182-91a85d80-4120-11e9-90cf-96f4d80bc1e8.png)
 This seems to solve itself when the LDS header is implemented. Could you confirm this?

**Comment by Luke1982** [comment]
Now that we've implemented the header, let's check if this behavior is solved

**Comment by joebordes** [comment]
it is, I tested it yesterday
thanks
