### ISSUE TITLE
How to override evvtmenu labels

### ISSUE THREAD

**Issue by partnerwerk** [tsolucio/corebos#526]
It seems to be impossible to customize the labels of the evvtmenu entries. The labels fall back to the respective translation of the currently active locale. It seems they get stored in the database but not displayed. Neither in the tree display on the menu module page nor in the final menu on top the page. Have you got a hint for me?

**Comment by joebordes** [comment]
Can you give me an example of what you are trying to do?
I see the complete menu in Spanish both in the header and in the menu editor.

**Comment by partnerwerk** [comment]
1. Adding a new menu entry I have four fields: type, name, action and parent.
1. As type (menu, module, url, etc.) I choose module.
1. I choose the module in field 3. Lets say "Products".
1. I click on add and the menu entry is created.
1. Now I want to change the title of the menu entry which the second field is for. It is automatically populated with the translation provided in the modules translation file. In my case "Produkte". But for some reasons I want to change it - after all there is a field for it. I type a new word, hit "Save" and it looks like it is saved, but it does not show up in the main menu and not in the list on the left side.

I hope this makes it clear...?

**Comment by joebordes** [comment]
Fixed:  https://github.com/tsolucio/corebos/commit/31d3ddcf49c5fb59c5378fd5b09ce574c8d33696

Thanks!

**Comment by partnerwerk** [comment]
Awesome. Thank you!
