### ISSUE TITLE
Creating a portal contact throws an error

### ISSUE THREAD

**Issue by JulianOtten** [tsolucio/corebos#530]
When I make a contact on the following page: http://localhost/corebos/index.php?module=Contacts&action=index&record=&relmodule=Contacts everything works fine, unless I add the "Portal User" checkbox. When I add this checkbox I get the following error:
![image](https://user-images.githubusercontent.com/32372051/55393257-3873f400-553d-11e9-93a9-d18d64f1b724.png)
I filled in the following fields:
* firstname
* lastname
* email
* checked portal user

afterwards I click save, thats when the error occures.

**Comment by joebordes** [comment]
the issue here is that it can't find the template to send the portal user information

if you have an up to date coreBOS go to the new Message Template module and create a template with the name 'Customer Login Details'

if you are still on the old templates go to settings > email templates and make sure you have a template with ID 10 that contains the message to send.

I added some code to not produce the error in case the template is not found. Thanks!

Let me know how it goes.

**Comment by JulianOtten** [comment]
So, after reading your comment I decided to update my localhosted corebos instalation with the newest version, just to make sure I am on the newest version possible. I wasn't able to find the Message Template module (probably because I am still fairly new to corebos), tho I did manage to gind the email templates: 
![mail-templates](https://user-images.githubusercontent.com/32372051/55405409-484e0100-555a-11e9-862f-6cd331451879.png)

After confirming that there is indeed a template, I decided to try and make a new contact with the "Portal User" checkbox, but I still got the same error.

I decided to also test on an online enviorment, which has IMAP support (I figured it *might* just be the case) and I also cloned the newest changes onto here. but after getting the right settings, I still keep getting the error (even tho error reporting is off on the online env, it throws a 500 error, which im pretty sure is the same one as on localhost) The only error I get on my online env is about php short tags.

I am also using an excisting email adres.

Hope this information was useful :p

**Comment by joebordes** [comment]
Ok, that gives me a clue: every time you update your coreBOS, even after a clean install, you must go to the coreBOS Updater, click on "load changes" and then click on "Apply All"

if you get some error, first try the "Apply All" again

once you do that you should see that the email templates are no longer there and they have been migrated to the new Message Template module

I would like to invite you to join the forum also as that is a better place for support questions.

You are also very welcome on gitter 

keep asking

**Comment by joebordes** [comment]
I am going to close this issue. Please feel free to comment about it on the forum or reopen if you need help.
