### ISSUE TITLE
Report - Filter date on related module

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#56]
Hi to all and thanks in advance to anyone that can help me.

I created a new custom report form the starting module "account" . Then i have inserted as related module "comments".

The report work fine but when i filter it with the date on related module the result is wrong. 
 * I put the date during the creation of the report.
 * I put standard filter "comment - date creation" last 7 days
and in this way the result is not correct

Can someone help me or someone has already solved this issue?
Thanks a lot

Mike

**Comment by joebordes** [comment]
Try this patch and let me know how it goes:

```
diff --git a/modules/Reports/ReportRun.php b/modules/Reports/ReportRun.php
index ecea02e..a0c4220 100755
--- a/modules/Reports/ReportRun.php
+++ b/modules/Reports/ReportRun.php
@@ -845,7 +845,11 @@ class ReportRun extends CRMEntity {
                                                                $tableColumnSql = "CAST((CONCAT(due_date,' ',time_end)) AS DATETIME)";
                                                        }
                                                } else {
-                                                       $tableColumnSql = $selectedfields[0].".".$selectedfields[1];
+                                                       if ($moduleName==$this->primarymodule) {
+                                                               $tableColumnSql = $selectedfields[0].".".$selectedfields[1];
+                                                       } else {
+                                                               $tableColumnSql = $selectedfields[0].$moduleName.".".$selectedfields[1];
+                                                       }
                                                }
                                                $startDateTime = "'$startDateTime'";
                                                $endDateTime = "'$endDateTime'";
```

Please try all you other reports that have filters on the dates, this change will affect the way they are generated. Hopefully for the better.

**Comment by micooro** [comment]
Thank you very much Joe,
your patch, after some problems, worked very good.
Your help was precious

**Comment by joebordes** [comment]
You welcome, I'm glad it worked. I would need you to share what problems you had and what you finally did so I can add it to coreBOS if possible.

Thanks

**Comment by micooro** [comment]
Ofcourse, what can i do to share this?
 

 
Da: Joe Bordes [mailto:notifications@github.com] 
Inviato: giovedì 9 luglio 2015 10:25
A: tsolucio/corebos
Cc: micooro
Oggetto: Re: [corebos] Report - Filter date on related module (#56)
 
You welcome, I'm glad it worked. I would need you to share what problems you had and what you finally did so I can add it to coreBOS if possible.
Thanks

**Comment by joebordes** [comment]
Well, basically tell me what you ended up modifying to get it working. If it was exactly the code changes I sent you or you had to change something else. The main idea is to add this fix to coreBOS so everybody using it get this problem solved.

Thanks

**Comment by joebordes** [comment]
Any follow up on this please?
