### ISSUE TITLE
Changing report filtering when on last page shows no results while they are present

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#566]
Say you are viewing a report that has 8 pages and you are on page 8. Then you change something in the on-the-fly filtering which reduces the result set to a lower number and basically eliminates the 8th page (because there are not enough results), the report will appear to have **no** results, while there certainly are results, just not on page 8 (because the new resultset doesn't have 8 pages).

Going back to page 1 first and then changing the parameters fixes this, but it is very confusing.

**Comment by joebordes** [comment]
I tried this and it worked correctly for me, in other words, the data table was reset to the first page.

I had a look at the code and see that [there is a time based change there](https://github.com/tsolucio/corebos/blob/master/modules/Reports/Reports.js#L1108). That type of code is always delicate as it may take more time depending on a lot of factors. I am tempted to move the `setTimeout` inside the `onRedraw` or to increment the 500 to 750 or 1000, but if you can reproduce the issue consistently it may be better for you to try those changes and tell me what is the correct amount for you.

**Comment by Luke1982** [comment]
Hmm, just ran into this again. I updated very recently so let me check the code you suggested

**Comment by joebordes** [comment]
closing
