### ISSUE TITLE
Product Discontinued when adding Product to Quote

### ISSUE THREAD

**Issue by reetp** [tsolucio/corebos#573]
User Created a new Quote in Browser Tab 1

Looked for and noticed a Product was missing and had to be added, so in Browser Tab 2 she added the Product.

Back in Tab 1 she went back, typed the Product name in the box, found it, and added it. 

However when she came to Save the Quote it threw an error saying Product Discontinued.

Either the Product should not be view-able or she should be allowed to Save.

**Comment by joebordes** [comment]
I can't seem to be able to reproduce this:  https://youtu.be/DbmPHTm0_VY

**Comment by reetp** [comment]
I'll go back and test.

It may be I am missing some changes.....

**Comment by reetp** [comment]
Nope - upgraded and that seems OK.

There are some other oddities but I'll look at those when I've had some sleep :-)
