### ISSUE TITLE
Anyone else notice open sessions?

### ISSUE THREAD

**Issue by gfxguru** [tsolucio/corebos#58]
I'm noticing a lot of extra sessions left open on server between localhost-mysql when running corebos. Anyone else noticing this? I'm testing CoreBOS and Vtiger 6.3. I have not noticed this with vtiger 6.3.  Any ideas?

**Comment by joebordes** [comment]
I haven't looked at that part of the code in a long time, but I remember adding code to destroy the session when the user logs out:

https://github.com/tsolucio/corebos/blob/master/modules/Users/Logout.php#L31

Are you logging out or is this just working normally?
