### ISSUE TITLE
[NFR] Cannot retrieve list of Inactive users

### ISSUE THREAD

**Issue by reetp** [tsolucio/corebos#598]
Note to self really.

If we do a simple query like:

doQuery("select user_name, id, status from users");

We will get back a list of users, but ONLY Active ones.

Ironically (and stupidly really) it returns their Status. Why, if they are only ever going to be Active? Illogical.

Logically you would expect Status to show both Active AND Inactive there. Yup, took me some long while to figure out I wasn't going mad.

The scenario I needed...

Get all invoices over the last 3 years with the user assigned so we can compare the sales of any given Organisation over 3 years.

We have user who have left and are inactive but they are still down as the assigned user on an Invoice so if there is ever any query we can see who did it.

It now means that I will have to do an individual retrieve for EVERY Invoice as the record gets parsed. A real resource hog and waste of cycles.

You also can't easily do things like 'List all SOs or Invs for Inactive Users'

If I ever get 5 minutes I'll try and see if we can't add a GV to enable this as I believe it is extremely important.

**Comment by joebordes** [comment]
fixed with this commit: a33048fb9bd6919cb31ba0cb1b3f7cb6c340130f

**Comment by reetp** [comment]
Thanks Joe.

FWIW I can see in the notes in some files it says "should Inactive be considered deleted" and I'd suggest the answer is never.

We have to keep records for 6 years legally for tax purposes and we need to know who the user was at the material time.

So they can be Inactive which mean they cannot login and change things, but their name is still against records where required.

If they leave we leave them against all documents eg Quotes, SOs, Inv, POs etc and JUST transfer ownership of Leads/Orgs/Contacts

Yes, after that period for GDPR you could consider erasing their name I guess - set it to anon1 or something. It doesn't have to be deleted entirely.
