### ISSUE TITLE
No php7 yet?

### ISSUE THREAD

**Issue by gfxguru** [tsolucio/corebos#609]
Why do you not support php 7 yet?

**Comment by Luke1982** [comment]
We do, for almost two year I think. What leads you to think we don't?

**Comment by joebordes** [comment]
exactly since December 2016 when we officially released the 7.0 support and we released 7.3 support at the beginning of this year (if I remember correctly).

so, @gfxguru what makes you think we aren't up to date?

**Comment by joebordes** [comment]
I'm going to close this issue and invite you to [continue discussing in the forum](https://discussions.corebos.org/).

**Comment by gfxguru** [comment]
you need to update your requirements page.

**Comment by joebordes** [comment]
Can you please tell me which page that is. The [one in the documentation](https://corebos.com/documentation/doku.php?id=en:install550) says it correctly (almost).

**Comment by omarllorens** [comment]
@joebordes I found this error on the next link. https://corebos.com/get-the-code/

**Comment by joebordes** [comment]
updated!  thanks!
