### ISSUE TITLE
Webservice accountid not accessible from accounts

### ISSUE THREAD

**Issue by reetp** [tsolucio/corebos#617]
Something is not quite right in the webservice queries for accounts.

I was picking up the account id from Invoices as 'account_id' but changed my query.

eg

select invoice_no, account_id from invoices
invoice_no -> INV1000
account_id -> 3x12345
id -> 16x12345

I then tried select 'account_id' from accounts (using 'account_id' as per Invoice queries)

select account_id from accounts
account_id   -> blank
id -> 3x12345

Hmm so I tried this:

select * from accounts
account_id -> blank
id -> 3x12345

I have a feeling that 'account_id' is misleading and should not appear in accounts queries because the 'id' is already there.

One of those things that if you know, you know, but if you don't it is illogical and causes you to start doubting yourself.

Confusingly, in the DB we have vtiger_account -> accountid 
:-)

**Comment by joebordes** [comment]
the way WS works is that it ALWAYS returns the ID of a record in the field  `ID`
if it is a foreign key in another module, it can be named whatever the person creating the foreign key wants.

So, in your case above:

INVOICE
 Primary Key:  ID  > 16x12345
 Foreign Key: account_id > 3x12345   this can be named whatever you want, it is just another field on the module, casually it contains a record number to another module

ACCOUNT
 Primary Key:  ID  > 3x12345

So you always search on the virtual `ID` field when using web services

HTH

**Comment by reetp** [comment]
No I get that.

But this should not happen.... account_id should not be there at all. 

I would not have noticed if I hadn't swapped from an Invoice query to an Accounts query and stupidly just assumed the field would be the same name.

So I had:

`select account_id, pl_net_total, invoicestatus  from invoice`

I stole some of that and mistakenly did:

`select account_id, industry, assigned_user_id from accounts`

And then looked for ['account_id'] which did not exist.

I then pasted that into the webservices console and noticed the column is found, when it should not be returned.

![Screenshot_2019-08-08_13-08-23](https://user-images.githubusercontent.com/3800384/62698563-b8273900-b9dd-11e9-9a93-854a56a3b8c3.png)

**Comment by joebordes** [comment]
account_id is the "Member of" field in Accounts module, it is "just" another foreign key. Casually with the same name as in the Invoice module
