### ISSUE TITLE
Document drag 'n drop does not work from outlook to firefox

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#636]
I've tested this:

Thunderbird attachment -> Firefox == OK
Outlook attachment -> Chrome == OK
Outlook attachment -> Firefox == Nothing happens

**Comment by joebordes** [comment]
Do you mean, dragging the attachment directly from the Outlook application?
I understand that if you save the attachment to disk and then drag it to FF it works, just like the thunderbird test, right?

**Comment by Luke1982** [comment]
Yeah directly from outlook doesn't work. From disk you only have the windows file explorer, that works fine with firefox.

**Comment by joebordes** [comment]
have you searched the internet for some issues with dropzone and outlook?

**Comment by Luke1982** [comment]
Honestly, no. Still crazy busy with a video and mainly created this as a reminder

**Comment by joebordes** [comment]
closing
