### ISSUE TITLE
Sorting on record No.'s in related lists

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#643]
When you sort on record no's in related lists, for example SO100 will end up higher than SO67 because it starts with a 1.

**Comment by joebordes** [comment]
see if this helps: http://corebos.com/documentation/doku.php?id=en:adminmanual:faq#automatic_number_fields_are_no

**Comment by Luke1982** [comment]
Well that's not going to help, since the numbering is based on the year. So we have for instance SalesOrder no's that range from 190001 to 199999 in 2019, and 200001 to 209999 in 2020. But we also have old orders that we numbered without a year prefix. Personally I believe that allowing the system to sort numberfields like text is counterintuitive, since people see the field as a number (regardless of the text-prefix) and expect to be able to sort it as such.

**Comment by joebordes** [comment]
I don't see why it wouldn't work with year prefix
the problem is not with the prefix but with the number, just add more "0"'s  before the increment and it works

**Comment by Luke1982** [comment]
The problem lies in the fact that we used to number records without the prefix and then switched to using a prefix. If we had started with the year prefix from the start, there would be no problem.

Regardless of my own problems in this particular case, I think a general user (I know I did) would expect TT2 before TT11 when sorting. Sure we can fix it by padding with numbers, but if you don't know that and start numbering and using the system, you end up with a lot of legacy records that won't sort properly. Personally I would always prefer a solution that doesn't require any explanation.

**Comment by joebordes** [comment]
well, I don't plan on making the list view retrieving and sorting of records seriously slower for this issue. The listview is already a pain point of speed in the application and it gets worse if you add events on the rows, if we add more exceptions and formatting on the internals of a field to sort it "correctly" it will get even slower. The solution of adding the zeros now, for all the legacy records is a better trade-off than hurting the day to day usability of the application forever.
It is a text field and it is sorted correctly using text alphabetical rules.

**Comment by Luke1982** [comment]
OK, wouldn't we benefit from planning a revamp of the related lists then? Or not really a revamp, but an alternative system that could slowly replace the relatedlists system one by one, using LDS, inline editing and all the good stuff?

**Comment by joebordes** [comment]
I think it isn't an issue of the output. In this case, we would have to create some SQL magic to tell MySQL to retrieve the records breaking the field in parts which will make it not be able to use indexes. The SQL time to GET the records would be very high and just keep growing as the number of records in the module grew. The solution would be to separate the prefix and the number parts (for ALL modules!) and even then you still have to take into account that the prefix should be indexed and sorted always as a two-field sort when you construct the SQL so we have to add code to query generator.

**Comment by Luke1982** [comment]
Looking at a query dump now:
```sql
SELECT vtiger_crmentity.*, vtiger_salesorder.*, vtiger_quotes.subject AS quotename, vtiger_account.accountname,
				case when (vtiger_users.user_name not like '') then CONCAT(vtiger_users.first_name,' ',vtiger_users.last_name) else vtiger_groups.groupname end as user_name
			FROM vtiger_salesorder
			INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_salesorder.salesorderid
			LEFT OUTER JOIN vtiger_quotes ON vtiger_quotes.quoteid = vtiger_salesorder.quoteid
			LEFT OUTER JOIN vtiger_account ON vtiger_account.accountid = vtiger_salesorder.accountid
			LEFT JOIN vtiger_groups ON vtiger_groups.groupid = vtiger_crmentity.smownerid
			LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id
			WHERE vtiger_crmentity.deleted = 0 AND vtiger_salesorder.accountid = 6000 ORDER BY vtiger_salesorder.salesorder_no ASC
```
This could surely be optimized, since this specific query was used to get 20 related SalesOrders, but the query retrieves many many more, since running it through phpmyadmin gets 92 records (and indeed takes a long time) when only 20 were needed. Just adding a LIMIT 20 to the end reduced the query time from 0.0020 to 0.0013.

I don't get what you mean when you say prefixes should be indexed. Could you elaborate?

**Comment by Luke1982** [comment]
This query (not the altered ORDER BY) produced the desired result without lengthening load time (actually reducing it, but I don't know why):
```sql
SELECT vtiger_salesorder.salesorder_no, vtiger_account.accountname,
				case when (vtiger_users.user_name not like '') then CONCAT(vtiger_users.first_name,' ',vtiger_users.last_name) else vtiger_groups.groupname end as user_name
			FROM vtiger_salesorder
			INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_salesorder.salesorderid
			LEFT OUTER JOIN vtiger_quotes ON vtiger_quotes.quoteid = vtiger_salesorder.quoteid
			LEFT OUTER JOIN vtiger_account ON vtiger_account.accountid = vtiger_salesorder.accountid
			LEFT JOIN vtiger_groups ON vtiger_groups.groupid = vtiger_crmentity.smownerid
			LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id
			WHERE vtiger_crmentity.deleted = 0 AND vtiger_salesorder.accountid = 6000 ORDER BY LENGTH(vtiger_salesorder.salesorder_no), vtiger_salesorder.salesorder_no ASC
```

**Comment by joebordes** [comment]
the correct way to do this would be to have two database columns per module autonumber field, one with the prefix and the other with the number. Then you create an index (mysql index) on the combination of both of them and then modify the code to generate SQL that does

`order by prefix,number`

if I remember correctly the "limit" is added to the query after showing it on screen for debugging

**Comment by Luke1982** [comment]
I agree, splitting over two columns would be the most logical solution. Maybe ordering by created date when sorting on record no.'s would also make sense since they will almost always match up I presume, as in the later created date will be represented by a higher number.

I see the LIMIT gets added at the end yes, missed that before. Let's see how we can speed up the perceived load time then (apart from enhancing the whole related experience) by for instance leveraging some JS template building. I mean, there's practically no way of reducing MySQL load times since the SELECT's won't decrease.

**Comment by joebordes** [comment]
I also agree with you, the "perceived load time" is really important and a place we CAN get some improvements as the Smarty engine is rather slow processing the rows.

**Comment by Luke1982** [comment]
Yes, moving to a JSON data object and building the frontend in JS will make it easier I think
