### ISSUE TITLE
Error: Quick Create ToDo

### ISSUE THREAD

**Issue by casati-dolibarr** [tsolucio/corebos#65]
Due Date should be greate than Start Date

Start Date: 2015-12-21
Due ate: 2015-12-31

Best regards

**Comment by joebordes** [comment]
Hi,

I don't know what you are trying to say with this. I tried the quick create and it seemed to work correctly for me. Can you please explain a little more?

**Comment by casati-dolibarr** [comment]
It does work as advertized. Closed.

(Apparently I've wrongly entered in sequence Start Date / Due Date ...)

Best regards

**Comment by joebordes** [comment]
:-)
