### ISSUE TITLE
update Exchange Rate Programmed Task Service

### ISSUE THREAD

**Issue by HenaHajderasi** [tsolucio/corebos#650]
The Yahoo exchange rate service API has been deprecated so we need to change the call to a new provider.  In the next forum thread ratesapi.io is proposed as an alternative.

https://discussions.corebos.org/showthread.php?tid=1594

Task: change the cron task to use ratesapi.io and validate functionality

**Comment by denaldd** [comment]
hi @joebordes, I want to work on this.

**Comment by joebordes** [comment]
great!

**Comment by denaldd** [comment]
PR: https://github.com/tsolucio/corebos/pull/667

**Comment by joebordes** [comment]
thanks!
