### ISSUE TITLE
Service Contract/Ticket relation in B2C

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#655]
- Deactivate the Accounts module
 - Open a Service Contract
 - goto more information and add a support ticket
 - the "related to" field should have the contact on the Service Contract filled in
 - when you save the ticket it should be related to the service contract

this process works as described if the accounts module is active but not if it is deactivated (B2C). Verify and fix if true.

**Comment by denaldd** [comment]
Hi @joebordes 
I have tried to verify this issue, and I found this:
In [this line](https://github.com/tsolucio/corebos/blob/master/include/utils/EditViewUtils.php#L59) when we have Accounts Module activated, num_rows is 2 so in this case call **getSalesEntityType** method, and we get Service Contract module, in other case when Accounts module is deactivated,  num_rows is 1, and we get results from query in this case, that is Contact(**relmodule**) and **entityid** is null, so in EditViewUI.tpl in var **$fldvalue.entityid** not have any value to relate with Service Contract

**Comment by joebordes** [comment]
thanks @denaldd, in the end, the issue was a variable named `parent_id` which is set in the related list was conflicting with the parent_id field on the helpdesk. I fixed it by forcing the value in the parent_id variable coming from the related list.
