### ISSUE TITLE
FieldDependency support multifield directives

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#659]
FieldDependency support multifield directives: many fields inside one action

The [Field Dependency Map](https://corebos.com/documentation/doku.php?id=en:adminmanual:businessmappings:field_dependency) currently supports one field per action:

``` XML
<dependency>
    <field>campaignname</field>
    <condition>[{...}]</condition>
    <actions>
        <change>
            <field>sponsor</field>
            <value>Sponzori</value>
        </change>
        <change>
            <field>campaignname</field>
            <value>2323232</value>
        </change>
        <hide>
            <field>targetaudience</field>
        </hide>
        <readonly>
            <field>campaignname</field>
        </readonly>
        <collapse>
        <block>sponsor</block>
        </collapse>
    </actions>
</dependency>
```

but for some actions it makes sense to permit defining many fields in one shot, so instead of:

``` XML
<dependency>
   ...
    <actions>
        <hide>
            <field>targetaudience</field>
        </hide>
        <hide>
            <field>campaignname</field>
        </hide>
        <collapse>
           <block>sponsor</block>
        </collapse>
        <collapse>
           <block>promoter</block>
        </collapse>
    </actions>
</dependency>
```

we should accept also the format

``` XML
<dependency>
   ...
    <actions>
        <hide>
            <field>targetaudience</field>
            <field>campaignname</field>
        </hide>
        <collapse>
           <block>sponsor</block>
           <block>promoter</block>
        </collapse>
    </actions>
</dependency>
```

Tasks:
 - modify the map to accept and process the new format. the idea here is to export the EXACT same format we are currently exporting so that we do NOT have to modify the field dependency code (javascript) itself. this is just an internal map change to make the life of the person creating the map easier.
 - modify the XSD to validate the new format

**Comment by AlbanaCelepija** [comment]
Hi Joe!
I would like to work on this issue.

**Comment by joebordes** [comment]
wonderful!  go for it!
(nice to see you around :-) )

**Comment by joebordes** [comment]
done.  thanks!
