### ISSUE TITLE
edit UIType 10 fields in Layout editor

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#660]
Permit adding and subtracting modules from uitype 10 fields in Layout editor. The next image is a proposed design option which can be adapted as needed:

![editUIType10](https://user-images.githubusercontent.com/1237191/65837650-50fd7500-e2fa-11e9-9aa0-4649e7c6dc17.png)

**Comment by mocodertz** [comment]
Hi @joebordes , I am interested to work on this issue.

**Comment by joebordes** [comment]
great!  go for it and ask whatever you need

**Comment by joebordes** [comment]
done.  thanks!
