### ISSUE TITLE
Deactivate activityreminder debug global variable

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#661]
We currently have a JS variable that permits us to deactivate the (rather annoying while you are debugging)  activity reminder call: [ActivityReminder_Deactivated](https://github.com/tsolucio/corebos/blob/master/include/js/general.js#L3160)

We must create a Global Variable to set the value of this variable without having to manually change it in the JS file.

[Similar to this](https://github.com/tsolucio/corebos/blob/master/modules/cbCalendar/cbCalendar.js#L11:L17)

Name the variable: **Debug_ActivityReminder_Deactivated** boolean with values 0 | 1 and 0 as default

**Comment by denaldd** [comment]
hi @joebordes, I want to work on this.

**Comment by joebordes** [comment]
great!

**Comment by denaldd** [comment]
PR: https://github.com/tsolucio/corebos/pull/665

**Comment by joebordes** [comment]
fixed!  thanks!
