### ISSUE TITLE
Error when trying to import .csv into Contacts

### ISSUE THREAD

**Issue by casati-dolibarr** [tsolucio/corebos#67]
Import starts (after properly completing steps 1 - 3) and then seems to hang indefinitely. Enabling PHP error tracking brought up:

Fatal error: Class 'PBXManagerAfterSaveHandler' not found in /var/www/corebos-master/include/events/VTEventTrigger.inc on line 140 

Best regards

PS: Import didn't offer a field Contact-ID to fil in from .csv!

**Comment by casati-dolibarr** [comment]
That's how the database looks like:
![Uploading Selection_827.png…]()
![Uploading Selection_828.png…]()

**Comment by casati-dolibarr** [comment]
That's how the database looks like:

See separate Email.

**Comment by joebordes** [comment]
Sorry for this. I decided to change the new handler name before commtting but I forgot to change it everywhere.
I just committed a fix: 2d6fefa7debb864702d1a428a993e1fde5bbd042

Please update your code and change the vtiger_events record class name to ```PBXManagerAfterSaveCreateActivity```

Probably something like:

```UPDATE vtiger_eventhandlers SET `handler_class` = 'PBXManagerAfterSaveCreateActivity' WHERE handler_class = 'PBXManagerAfterSaveHandler';```
