### ISSUE TITLE
Not can configure mail sending

### ISSUE THREAD

**Issue by danicabrera84** [tsolucio/corebos#675]
I am trying to configure the sending of mail in corebos but it keeps loading and does nothing to me, my configuration is that of ionos and it is correct since it is the same as I have in the mail manager

**Comment by joebordes** [comment]
some ISP limit the access of SMTP and you have to modify the code as [explained here](https://corebos.com/documentation/doku.php?id=en:adminmanual:outgoingserver)

On that page, you can also read that you can set the Debug_Email_Sending global variable and activate application debugging to get the full output of the email conversation in the log file. That should show you where the error is.

Be careful with sharing that information here as passwords are shown. If you can share the error message maybe we can help a little more.

Also, have a look at some of the other settings for Microsoft exchange, google gmail, and sendgrid maybe one of those helps.

Let us know how it goes.

**Comment by joebordes** [comment]
I'm going to close this issue, if you need any further help, ask in the forum or reopen this issue
