### ISSUE TITLE
Mobile Interface Not Showing

### ISSUE THREAD

**Issue by dfanaei** [tsolucio/corebos#676]
Hi, 
First, let me thank you for the hard work you guys have put into this. it is really showing how functional the CRM is. it is simple and I haven't really seen many problems with it. 
Your system is Certainly better than YF or any other Vtiger inspired CRMs out there that are produced by some arrogant developers. 

I have only faced this issue for now:
When I add /mobile.php to the CRM URL, it says "Not Found". 
The Module is already enabled in the settings. 
Is there a fix for this?

Thanks in advance

**Comment by omarllorens** [comment]
Thank you, we are glad you appreciate our work. :-)
Respect Mobile, exist two url to access:
http://corebos/Mobile.php
http://corebos/modules/Mobile

I supposed that your problem is that you wrote **m**obile.php and the correct is **M**obile.php
