### ISSUE TITLE
JqueryVersion : Event.observe error on some files

### ISSUE THREAD

**Issue by mslokhat** [tsolucio/corebos#68]
Hi,

seems the function still there :

- Helpmenow.js
- Calendar4You/ EventEditViewContent.tpl
- MailManager/ index.tpl
- ActivityEditView.tpl
- Home/FirstTimeLogin.tpl

**Comment by EdliraDushku** [comment]
Hi,
I really appreciate your time for proving us this feedback. It is quite important for fixing and improving the migration of coreBOS from Prototype to JQuery.
From today, JqueryVersion branch is up-to-date and also the mentioned files are updated with the equivalent of Prototype's Event.observe in jQuery.
It will be very helpful if you can test this branch again and see if everything is working as you expected.

Thanks a lot for your time
Edlira

**Comment by joebordes** [comment]
I validated this, it is correct now
