### ISSUE TITLE
PDF Templates for invoices and other modules

### ISSUE THREAD

**Issue by dfanaei** [tsolucio/corebos#680]
I have been having a bit of a hard time understanding how the pdf Templates work in corebos. 
In vtiger, I used to use the PDF Maker module. as you perhaps know, it had a whole set of tools to design any document and almost as many as we needed for each module and then when you wanted to export, it would give you a choice on which template you would like to print or attach to the email. 

What I am trying to do here is the same. I know it is perhaps done in a different way in corebos but just can't figure it out. Is there any tutorial on how to do this? I couldn't find any info in the documentation. 

I basically would like the sales agents to be able to send emails with pdf attached and be able to choose a specific template to be attached. 

It would be much appreciated if you can help me out with this as I have no idea where to go for this. 

Also, if this is possible to do, Where can I find the PHP Variables to add to template?

Thanks,

**Comment by inapetani** [comment]
Hi there!
In CoreBOS we use the GenDoc extension to generate documents for any module. To access this extension and add it to the modules that you want, you need to go to the Module Manager and click on the Settings icon of the costum module Generate Documents.
At this point by going into the Activated Modules section you can select all the desired modules for which you want to generate documents, for example Invoice. By activating the GenDoc extension for the Invoice module now you can go to any record of this module and email or export the documents that you need to.
Some more information about what you asked can be found here: https://corebos.com/documentation/doku.php?id=en:gendoc:gramatica
Also by searching with the keyword GenDoc into the coreBOS documentation you could get a clearer vision of this extension.
Thank you,
CoreBOS team

**Comment by Luke1982** [comment]
Also, if you really want the PDFMaker extension (although I would recommend GenDoc), you **can** use it. I think there is a special version.

**Comment by joebordes** [comment]
Yes, PDFMaker works too. If you need it, contact me and I will send you the adapted version, but as Luke says, GenDoc is the official way to do this, it is supported and an active project that keeps getting enhancements. PDFMaker is just maintained "as is" for those people coming from vtiger crm.

HTH

**Comment by dfanaei** [comment]
@inapetani @Luke1982 @joebordes Thanks very much for your help with this. I figure out how to get the Gendoc to work with the invoices. It's actually really cool! I think it is better than the PDF Maker for the Templates. However, The one problem we are having is that it only exports to ODT, It also attaches ODT file in the email. Customers will have an issue receiving ODT files as it is editable. Is there a setting to change the file format to PDF?

**Comment by joebordes** [comment]
Glad you like it. I find it easier to understand than haking HTML.

In order to transform the ODT to PDF you have to install and configure OpenOffice headless in your server. The process isn't very complicated but has it's learning curve. Ask google for some tutorials

If you don't want to do that you can purchase the corebos subscription https://corebos.com/documentation/doku.php?id=en:extensions:extensions which includes the PDF conversion functionality on our servers AND a lot of modules.

http://blog.corebos.org/blog/corebossubscription

**Comment by dfanaei** [comment]
Thanks, @joebordes 
I have installed LibreOffice headless, however, is there a script that needs to be run? I mean, what do I really need to connect it to? I am assuming corebos doesn't automatically connect to LibreOffice? By the way, It is installed on the same server. I see in the settings it is asking for an external server. Is it ok if it's installed on the same server?

**Comment by joebordes** [comment]
see if this conversation helps and let us know

https://discussions.corebos.org/showthread.php?tid=1404

**Comment by dfanaei** [comment]
Ok so we did what was discussed in the conversation but it didn't work.

libreoffice headless is working
![libre1](https://user-images.githubusercontent.com/29267557/68098708-22cc0180-fe73-11e9-822f-d9afd45d86a9.png)

Table was modified to include new values like described in forum
![table1](https://user-images.githubusercontent.com/29267557/68098720-4000d000-fe73-11e9-9209-205527cbeac8.png)

Table original wasn't required values. an new table
![table2](https://user-images.githubusercontent.com/29267557/68098755-70e10500-fe73-11e9-9817-55bd2623da6f.png)

corebos is showing pdf buttons, **However, It is not generating the PDF Files.**
![core1](https://user-images.githubusercontent.com/29267557/68098795-a8e84800-fe73-11e9-8491-c2a17faf4e7c.png)

**Comment by joebordes** [comment]
this part of the code:  https://github.com/tsolucio/corebos/blob/master/modules/evvtgendoc/OpenDocument.php#L2725

seems to indicate that it will try to execute the unoconv program to convert the ODT into a PDF. For that to work, I suppose that you will have to make sure that the webserver user can find and execute it.  Try that

**Comment by dfanaei** [comment]
Unfortunately, This also did not work.

**Comment by joebordes** [comment]
it is most probably because the webserver user (the one actually executing the unoconv script) does not have permission to do so. By default, this user doesn't even have shell access.

If you want us to install it for you, send an email to comercial@tsolucio.com, we will have our devops team member set it up for you.

**Comment by dfanaei** [comment]
Thanks @joebordes . I just emailed you. 
Corebos is running under www-data. I believe the right access permission is given. Unoconv and headless Libreoffice are both running as well, but it still doesn’t generate the pdf.

**Comment by dfanaei** [comment]
Hi. I still haven't got an email back from your team. Does anyone know a fix? It would be greatly appreciated.  Thanks

**Comment by joebordes** [comment]
strange. look for me on gitter or slack and we'll find out what is going on

**Comment by dfanaei** [comment]
How can I find you on slack?

**Comment by joebordes** [comment]
joebordes

**Comment by joebordes** [comment]
I added a coreBOS channel

**Comment by dfanaei** [comment]
Ok. But slack is team specific. Doesnt let you add other slack members. Unless if i invite you to my slack workplace by entering your email (which i dont have)

**Comment by joebordes** [comment]
https://join.slack.com/t/joebordes/shared_invite/enQtODQxODI0MTg3MjY0LTFlOGZmOTUyYTM0NDNlYmY5MjVhNDRhNzdlODBkOWEzMDk1ZmE5YTdjYjFkN2UxYjMzNzJkMjE2MjQ3ZjY1OTI

**Comment by dfanaei** [comment]
Hi @joebordes, did you have a chance to check this? Let me know if you need more info provided. Thanks

**Comment by joebordes** [comment]
no, not yet. it is on my list

**Comment by dfanaei** [comment]
do you have an idea on the timeline?

**Comment by joebordes** [comment]
no, but I have it in front of me. if you want to get paid support let me know and I will put you in contact with the team

**Comment by dfanaei** [comment]
I already emailed your team a while ago for this I didn't get a reply back. I will sort it out. Thanks.

**Comment by joebordes** [comment]
in the end, it was a unoconv issue: we had to execute

`unconv --listener`

as a background task
