### ISSUE TITLE
Listview columnsearch is funky when column holds UI10 fields

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#688]
This is one I seem to be the only one having trouble with, but I'd really like to try and get work done on this soon. Since autocomplete was introduced on the searchboxes at the top of the columns in listview, it all goes to hell when that column holds UI10 fields. Need to do more testing to see what parameters you need to reproduce but I'll dig into this soon.

**Comment by Luke1982** [comment]
![Peek 2019-11-12 21-49](https://user-images.githubusercontent.com/8875222/68709660-75ee3480-0596-11ea-9ac0-e31a560ceb65.gif)
Here's a peek that shows that listview column searching doesn't work at all for the vendors column in PO's. This is a clean installation with the test DB.

**Comment by joebordes** [comment]
could it be related to the filter? => does it work with the ALL filter?
what is the SQL being generated?
any error in the debug log file?

**Comment by Luke1982** [comment]
> could it be related to the filter? => does it work with the ALL filter?

The peek gif is a stock installation with the test DB, using the ALL  filter.

> what is the SQL being generated?
> any error in the debug log file?

Let me check those and report back. I have another installation where this happens. Manually reverting [this](https://github.com/tsolucio/corebos/commit/27a5c2c38ec790c8bd3f57edcbe9502f5adc6c4d#diff-802db39a537b3facadf682961e6038fa) commit fixed it so that's where I'm going to start searching.

**Comment by Luke1982** [comment]
It seems the error occurs because there is some SQL that is triggered **before** the actual search SQL is triggered. For instance:
```sql
SELECT SQL_CALC_FOUND_ROWS vtiger_purchaseorder.purchaseorder_no, vtiger_purchaseorder.subject, vtiger_purchaseorder.vendorid, vtiger_purchaseorder.tracking_no, vtiger_purchaseorder.total, vtiger_crmentity.smownerid, vtiger_purchaseorder.purchaseorderid FROM vtiger_purchaseorder  INNER JOIN vtiger_crmentity ON vtiger_purchaseorder.purchaseorderid = vtiger_crmentity.crmid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id LEFT JOIN vtiger_groups ON vtiger_crmentity.smownerid = vtiger_groups.groupid LEFT JOIN vtiger_vendor  ON vtiger_purchaseorder.vendorid = vtiger_vendor.vendorid  WHERE vtiger_crmentity.deleted=0 AND   (  (( trim(vtiger_vendor.vendorname) = 'Vernon') )) AND vtiger_purchaseorder.purchaseorderid > 0 LIMIT 0, 40
```
Was a result of my query to 'Vernon' in the vendors column when searching in PO's. The should be a LIKE clause since I want to be able to search on part of a string, not only on the entire, correct string.

**Comment by Luke1982** [comment]
But we've got more trouble:
![Peek 2019-11-17 15-15](https://user-images.githubusercontent.com/8875222/69008650-2e2c2c00-094d-11ea-92d5-657601cd241e.gif)
This is also in a stock corebos, default test DB. The autocomplete returns the Account ID in stead of the name.

**Comment by Luke1982** [comment]
OK, so I found a bit more. The search uses the advanced filtering mechanism. When I search for 'Marlow' in the Vendors column in PO's, this is the filtering that is applied, taken *directly* from the request:
```json
[{"groupid":1,"columnname":"vtiger_purchaseorder:vendorid:vendor_id:PurchaseOrder_Vendor_Name:V","comparator":"e","value":"Marlow","columncondition":""}]
```
Note that the comparator, set [here](https://github.com/tsolucio/corebos/blob/master/include/js/ListView.js#L187), is an 'e' for equals, where when you change that to a 'c' for contains, the old, correct behaviour returns.

**Comment by Luke1982** [comment]
OK I fixed the reference field thing in [this](https://github.com/Luke1982/corebos/commit/aff94408d9daee0af682db1613e926b0f213a488) commit I think. Now to optimize the autocomplete.

**Comment by Luke1982** [comment]
OK this issue can be closed now since all the issues have been addressed in [this](https://github.com/tsolucio/corebos/pull/689) PR

**Comment by Luke1982** [comment]
Hmm, not quite yet. It seems in some cases the autocomplete still returns CRM ID's in stead of the textvalue
![Peek 2019-11-23 11-09](https://user-images.githubusercontent.com/8875222/69477038-c1e47900-0de1-11ea-89ff-2779d9cc1bb0.gif)

**Comment by Luke1982** [comment]
> Hmm, not quite yet. It seems in some cases the autocomplete still returns CRM ID's in stead of the textvalue
> ![Peek 2019-11-23 11-09](https://user-images.githubusercontent.com/8875222/69477038-c1e47900-0de1-11ea-89ff-2779d9cc1bb0.gif)

This has to do with legacy reference fields in SO's, like UI types 73, 78...

**Comment by Luke1982** [comment]
OK, it seems all the tests that previously failed now all work out. I'm gonna close this.

**Comment by joebordes** [comment]
great!!
remember to have a look at all the account and contact capture fields in Inventory modules and Account (member od) and Contacts (reports to). Make sure they are working as you want.
