### ISSUE TITLE
Currency Separator + Variable/Field Name List

### ISSUE THREAD

**Issue by dfanaei** [tsolucio/corebos#692]
Hi, Is there a way to change the currency separator from Comma to dot in Gendoc? I have set the currency to USD but in Gendoc it shows Comma. 

Also, Do you know where I can find the list of field names or Variables ( Ex. {Products.productname}) to use in the document templates?

One issue I am facing at the moment is that in one of the invoice templates, it has  {Products.description} in the table, which must show the product description, However, if the product itself has no description by default and you add the description as you are writing the invoice, it won't add it in the ODT or the PDF as {Products.description} is pointing to the description in the product page but not the product comment field in the invoice. So I thought {InventoryDetails.comment} or {InventoryDetails.description} should work, but it doesn't. So if there were a list of these field names or if there is a way to find out these names/variables, It would be really nice. 

Thanks,

**Comment by joebordes** [comment]
I [made this change](https://github.com/tsolucio/corebos/commit/460fec89020d66ef463cc50bac721169f6c59b41) so user preferences apply to the numbers now

**Comment by joebordes** [comment]
In the Tools menu, you will find the "Merge Labels" extension with all the supported labels and a copy/paste button. What I do sometimes is open this extension in a window, make it small, or long, like a toolbar, then I set it fixed on top so it always shows and then hover it over the open office document template while I type.

**Comment by joebordes** [comment]
AFAIK the comments of each inventory line are copied to the InventoryDetails.description field, so that one should work. Make sure you have written it correctly and clean the format. Also, look in the inventory details records themselves to check if the comment is there.
