### ISSUE TITLE
Document access without edit and remove

### ISSUE THREAD

**Issue by dfanaei** [tsolucio/corebos#693]
_Hi 
First of all, I would like to thank this community specially Joe for being really supportive on issues that I have opened here so far. 
Sorry if I am bringing here lots of points and questions, Hopefully it will help add to the information database for future users._ 

Is there a way to give a user group (Let's say the "Management")the ability to add certain documents that are only visible to other users but not editable or removable? 
This feature would be for certain documents that sales people can send to clients or access for information but won't be able to edit or remove. 

Thanks,

**Comment by joebordes** [comment]
Thanks for the positive comments :-)
I am sure that your questions will be helpful to others.
In this case, the answer is yes, that can be done. I would recommend you start by reading the [Security Guide](https://corebos.com/documentation/doku.php?id=en:adminmanual:securityguide) and try to configure the system to do what you need. Then open another issue with any particular problems you may run into.

**Comment by dfanaei** [comment]
Thanks @joebordes .
I have been customizing Roles, Profiles, and Group, as well as Sharing Access. It is ofcourse great as it will let certain records to be private and gives ability to management to view and edit employees records. However, when it comes to the Documents, The ability to make a certain folder or document Viewable to others (But not deletable/editable) is not there. Or atleast I don't see it. 
The only way I figured would be to "assign to", however, this will still give the user group the ability to edit or delete the documents. 
A way I was trying to see if this could be possible, was to create a checkbox called "Public View" and then using the business map module to enable the files that have the checkbox checked to be viewable by everyone. However, I simply can't figure out what to do to make this happen if it is even possible. Is this a possible way to approach? if yes, do you know the instructions? 
or if not possible through business maps, how can I make this possible?

**Comment by dfanaei** [comment]
Wow! I actually found the answer. Thanks for the documentation and videos you have provided. 
If anybody faces this, you can learn here: https://www.youtube.com/watch?v=Iryw1xw78t4
