### ISSUE TITLE
Mail Manager Setup

### ISSUE THREAD

**Issue by dfanaei** [tsolucio/corebos#695]
Hi, 
I am trying to setup MAil Manager. Our emails are hosted through Yandex Mail. 
https://yandex.com/support/mail/mail-clients.html
In the link above, It shows the Imap server info. When I enter the info including username and pass, unfortunately, the mail manager doesn't respond. it starts loading for a bit and then nothing happens. 
I am sure all the info I enter is correct, however, there is no option in Corebos to enter Port #. Could this be the issue?

**Comment by joebordes** [comment]
make sure you have php-imap installed and check the logs for errors that will tell you what is happening.

**Comment by dfanaei** [comment]
php-imap is installed. 
Is this where I check the log file? sudo tail -100 /var/log/apache2/error.log

**Comment by joebordes** [comment]
yes
you can also activate debug log in corebos

**Comment by dfanaei** [comment]
This got fixed. It was an issue with the yandex server. I had to to use .ru instead of .com. Kind of weird.
nothing wrong with Corebos.
