### ISSUE TITLE
Business Map Field Dependency Doesn't Work 

### ISSUE THREAD

**Issue by dfanaei** [tsolucio/corebos#696]
Ok So I have been adding Business Maps for Record Access Control and adding Workflows etc. It has been working fine. So it means Business Maps Module Works for me. 
However, Now I am trying to get some of the fields to Show/Hide Depending on the values of other fields. ( I already chose Map Type: Field Dependency)
The problem is that no matter what I do and How I set the conditions, Nothing applies. I even tried to copy the exact same examples you have in the documentation to see if it works at all, but It didn't. 
Is there a php Extension or something I am missing?

Below are the screenshots of the business map and the Payments Field

![BM1](https://user-images.githubusercontent.com/29267557/71512739-64ae6e00-284c-11ea-892c-1fab88a7f06d.jpg)

![BM2](https://user-images.githubusercontent.com/29267557/71512748-6aa44f00-284c-11ea-86bd-cb409f7017ac.jpg)

**Comment by joebordes** [comment]
Almost all the maps are triggered by their name. The important field is the name of the map. In this case the name of the map must be:  **[modulename]_FieldDependency**

**Comment by dfanaei** [comment]
I see. What about if we are creating multiple maps for the same module? is it ok if it has duplicated names?

**Comment by dfanaei** [comment]
Ok so the Payments Module actually worked when I changed the Name. However, Now as I am trying to create one for the Documents Module, It seems not to work. I believe I have done the same as you did in the Video Tutorial. Here are the Screen Shots:

Note: it doesn't work regardless of what I set for "Comparator". I have tried "e" , "c" , and "s".

![BM3](https://user-images.githubusercontent.com/29267557/71515639-1e134080-2859-11ea-9837-42f0746c91b0.jpg)

![BM4](https://user-images.githubusercontent.com/29267557/71515642-22d7f480-2859-11ea-86a9-839389652ddb.jpg)

**Comment by joebordes** [comment]
In most cases there can only be one map, AFAIK the first one found with the established name will be used.
Now, that said, this is, in reality, the default map that will be used. Most business maps are designed to be used per user/role. The decision of that is made in the Global Variable module because GV module already has all the logic and escalation rules to decide which record to use in each case. So, what we do is search for the map going through the GV module. If none is found there we load the default name.

So, you should be able to define a GV with the name **BusinessMapping_[modulename]_FieldDependency**, select there the business map you want to apply when that record is selected and name the business map whatever you want.

**Comment by joebordes** [comment]
Please share the map for Documents here in text, so I can copy-paste it and give it a try.

**Comment by dfanaei** [comment]
Thanks. Here you go.

<map>
  <originmodule>
    <originname>Documents</originname>
  </originmodule>
<dependencies>
<dependency>
    <field>folderid</field>
    <condition>[{"groupid":"",
"columnname":"vtiger_notes:folderid:folderid:Documents_Folder_Name:V~O",
"comparator":"e",
"value":"Resources",
"columncondition":""}]</condition>
    <actions>
        <hide>
            <field>template</field>
        </hide>
    </actions>
</dependency>
</dependencies>
</map>

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by joebordes** [comment]
the folder picklist is special and was missing some code. I added the change to corebos so if you update your code and set the value to the numeric value of the folder (open the select and look at the option values) it will work for you.

Thanks for informing.
Let us know how it goes.

**Comment by dfanaei** [comment]
It works now! Thank you.
