### ISSUE TITLE
Documents "Add Folder" Permissions

### ISSUE THREAD

**Issue by dfanaei** [tsolucio/corebos#698]
Is there a way we can change the permission for adding/Removing Document folders for each Role/Profile? 
I believe Adding Folders are a part of Documents Module, However, There is no option to edit its' permissions. 
Can this be done through RAC Business Map?

**Comment by joebordes** [comment]
no, there isn't much you can do there. that was a typical after-thought mess released in the vtiger crm false open source project that we have not dedicated any time to.

**Comment by dfanaei** [comment]
is there atleast an option to disable the "Add Folder" Button for a user Profile?

**Comment by joebordes** [comment]
No, nothing. Sorry.
We can dedicate some time to it if you want but the biggest problem is all about deciding how that should be solved completely, like real folder management with nested folders, ...

**Comment by dfanaei** [comment]
Yes it would be a good option perhaps for later. Please let me know what the cost to add this would be in Slack and I can perhaps contribute financially later on in the future to fix this.
