### ISSUE TITLE
Gendoc: add sorting in foreach

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#708]
I can't figure out the mechanics of the foreach in gendoc. I know it has something to do with [this](https://github.com/tsolucio/corebos/blob/master/modules/evvtgendoc/OpenDocument.php#L1073-L1091) part and many other parts. I also know it uses the '[default](https://github.com/tsolucio/corebos/blob/master/modules/evvtgendoc/compile.php#L793)' related list query but apart from that, it uses a whole bunch of global variables stringing it all together.

Anyway, the point is, you have no control over how you want your records to appear on the template. Let's say on a certain template you want to sort the timecontrol records sorted by their start dates, you have no control to do that.

OK, note: `eval_paracada` is meant to populate the global `$iter_modules` which at some point will be injected back into the template.

An alternative, less pretty method could be to feed an alternative related list function name that overrides the default one to the code. But that would require you to write a special related list function for each special action you would want to take, even as simple as sorting.

**Comment by Luke1982** [comment]
Note: [getRelatedCRMIDs](https://github.com/tsolucio/corebos/blob/master/modules/evvtgendoc/compile.php#L1700-L1710) in compile.php can maybe be altered to add an additional sorting parameter.

**Comment by Luke1982** [comment]
syntax proposal
`{foreach CobroPago [paymentcategory=MyPaymentCat && credit=1] *date_start ASC*}`

**Comment by Luke1982** [comment]
PR that allows sorting [here](https://github.com/tsolucio/corebos/pull/710)

**Comment by joebordes** [comment]
accepted. thanks Luke!
