### ISSUE TITLE
Tracker needs two clicks at endpoint, should react right away

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#727]
https://github.com/tsolucio/corebos/blob/59c0cd002f30a40bb9557ad24db41af14d50a71d/modules/ModTracker/ModTrackerCommon.js#L111-L117

When the tracker has no more history to show in any direction, it shows a message. But you need to click twice before you get the message in stead of once. Should improve that for better UX.

**Comment by Luke1982** [comment]
Hm, this is not a problem with the new tracker implementation. It seems that multiple 'atpoints' produce the same result sometimes. I never got into how the tracker works but it seems it can store duplicate entries sometimes. Not a frontend issue but I think very hard to find...

**Comment by joebordes** [comment]
maybe just a test-data issue. When I created the coreBOSTest database I did not always follow the rules. I did some direct inserts and duplicated information simply because it was easier.

Let's close this and open an issue if we do find some duplicates somewhere

**Comment by Luke1982** [comment]
Nah it does that in a regular installation as well, but again, not a big deal. Not worth the time right now
