### ISSUE TITLE
ModTracker shows user ID's in stead of names and unformatted no.'s

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#732]
The user ID thing only happens sometimes, need to figure out when that happens.

**Comment by joebordes** [comment]
keep me informed about this as I have plans to make some changes wrt highlighting so if you catch where that is happening I will fix it

**Comment by joebordes** [comment]
I made some changes here because I didn't like the way highlighting was being handled. While I was at it I started using an internal ModTracker function which seems very intelligent about field types instead of the default we were using. Have a look as I think I may have fixed this issue.

**Comment by joebordes** [comment]
closing
