### ISSUE TITLE
Mobile settings doesn't load correctly on first load

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#742]
When you open the Settings section in the mobile UI it doesn't load correctly: it is missing the handlers to sort the modules and if you click on any setting it does not launch the save.
If you reload the page it starts working as expected.

![MobileConfigError](https://user-images.githubusercontent.com/1237191/77239193-fd4c5400-6bd7-11ea-95be-15147c2e3851.gif)

**Comment by joebordes** [comment]
@omarllorens can you have a look at this, please?

**Comment by omarllorens** [comment]
Ok, I will check it.
