### ISSUE TITLE
mobile - invalid id when click on email task

### ISSUE THREAD

**Issue by slemernet** [tsolucio/corebos#746]
After login, the systems will show tasks associated with the user

I have a workflow that sends an email to the user when a new ticket is created (via mailscanner)

when the user clicks on one of these tasks, the system (it is not the tiecket that was created, but the email task) shows id specified is incorrect
![mob4](https://user-images.githubusercontent.com/47395137/77343600-b150fa80-6d10-11ea-8a96-beae8adcc412.gif)

**Comment by omarllorens** [comment]
Hi @slemernet. I've tried to fix this, but I've seen that I can't reproduce the error. Maybe the last updates fixed this. Can you update and try again, please?
![mobile-calendar-emails](https://user-images.githubusercontent.com/7083757/82991657-4d8fca00-9ffe-11ea-9731-28a93771d43a.gif)
