### ISSUE TITLE
CSRF prevents ES2017 fetch

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#747]
I haven't looked into this any further yet, but when I perform an AJAX call within the application through the modern fetch API (in this case a POST), it leads me to the CSRF error page. A regular XMLHttpRequest does the trick.

Maybe we need to update some library?

**Comment by joebordes** [comment]
You have to send in the CSRF credentials

https://github.com/tsolucio/corebos/blob/master/modules/com_vtiger_workflow/resources/fieldexpressionpopup.js#L375
https://github.com/tsolucio/corebos/blob/master/modules/com_vtiger_workflow/resources/fieldexpressionpopup.js#L387

that example should suffice. If so, please close the issue, if not, share your call with us.

**Comment by Luke1982** [comment]
I figured something like that, but I don't get why a regular XMLHttpRequest doesn't need that

**Comment by joebordes** [comment]
CSRF overrides the object and adds it for us automatically. It does that also with jQuery
fetch didn't exist when CSRF was created and last time I looked that library hadn't been updated.

**Comment by joebordes** [comment]
https://github.com/ezyang/csrf-magic
Latest commit 7365929 on 28 Mar 2016

**Comment by Luke1982** [comment]
OK so let's close this then.
