### ISSUE TITLE
Tooltip causes a fatal error when date fields are shown

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#748]
I probably introduces this when I converted time fields to handle more than 24 hours (since they were supposed to be accumulated time, not Time Of Day fields). Some function tries to handle it as a TOD value causing a fatal error

**Comment by joebordes** [comment]
I can't seem to reproduce this. Can you tell me what field you are having problems with?

**Comment by Luke1982** [comment]
As you pointed out on gitter, this is more probably a problem with the field defaults
