### ISSUE TITLE
activity reminder issue on jqueryversion

### ISSUE THREAD

**Issue by mslokhat** [tsolucio/corebos#75]
Hi,

when using the jqueryversion. no reminder pops up on the screen

seems the issue come on general.js file
line 3107

if(typeof(Ajax) == 'undefined') {
		return;
	}

**Comment by joebordes** [comment]
this should be fixed now on that branch

we have been testing and validating the jquery branch this week, it is production ready and will be merged into the master branch shortly.

Thanks for informing.
