### ISSUE TITLE
File does not exist softed/images/clock_bg.gif

### ISSUE THREAD

**Issue by reetp** [tsolucio/corebos#759]
A small irritation...

softed/images/clock_bg.gif

File does not exist: ...../crm/html/themes/softed/images/clock_bg.gif, referer: https://mycorebos.com/index.php?action=index&module=Invoice

File is in /themes/images but not in themes/softed/images

Only place this might occur is here

https://github.com/tsolucio/corebos/blob/master/Smarty/templates/Clock.tpl

Only seem to be two references.

`dsp5.backgroundImage="url(themes/images/clock_bg.gif)";`

Which is correct so must be $IMAGEPATH ?

`<div style="background-image: url({$IMAGEPATH}clock_bg.gif); background-repeat: no-repeat; background-position: 4px 38px;" id="theClockLayer">`

**Comment by joebordes** [comment]
thanks
