### ISSUE TITLE
Reports Configuration Step 7 style error

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#77]
Using Chrome.
In step 7 of creating/editing a report the standard conditions are hidden but the height of the hidden rows is respected as a big blank space. The div inside the rows are hidden but the rows aren't so, for some reason the height the div will have is reserved.

![errorcfginformechrome01](https://cloud.githubusercontent.com/assets/1237191/15752838/3160e352-28f0-11e6-9683-0037cdc26188.png)

![errorcfginformechrome02](https://cloud.githubusercontent.com/assets/1237191/15752839/3277e650-28f0-11e6-8a73-04a4675026d6.png)

In Firefox this looks correct:

![errorcfginformefirefox](https://cloud.githubusercontent.com/assets/1237191/15752851/400dcece-28f0-11e6-946d-b2c81788e632.png)

**The code is in:**

Smarty/templates/ReportFilters.tpl

**Comment by kikojover** [comment]
For some (unknown) reason Chrome sets height of rows, either hidden or visible. I've setted in each tr a height of 1px.

Tested on Chrome and Firefox.

**Comment by joebordes** [comment]
Looks great!
Thanks!
