### ISSUE TITLE
Unused code for multicurrency

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#814]
https://github.com/tsolucio/corebos/blob/2fe89510c6c4dc056af117246ff1d4e06346ff58/include/js/Inventory.js#L1687-L1692

I'm going to remove what you added [here](https://github.com/tsolucio/corebos/commit/2fe89510c6c4dc056af117246ff1d4e06346ff58#diff-dc52855ef3d2e5662b79a6512e087a12R1687-R1692) since it doesn't do anything. What we use now is the callback so the current code never comes here, it uses the `else` and the original setup does not have multicurrency support yet so I'll add that later.

**Comment by joebordes** [comment]
fixed
