### ISSUE TITLE
Workflow Tasks E-Mail - Recipient field is not stored

### ISSUE THREAD

**Issue by partnerwerk** [tsolucio/corebos#838]
When changing a workflow email task the recipients email address will not get stored. If updating existing tasks the recipients email address field is emptied. 
I can set up new tasks and the same happens again. Everything else gets stored.
This made essential workflows unusable. Does anyone have an idea, if this is a bug or where I have to check my installation? There is no mysql error though.

**Comment by joebordes** [comment]
is your code up to date? I think we fixed this one a while back

**Comment by partnerwerk** [comment]
Yes, it is updated. But the error still occurs.

**Comment by joebordes** [comment]
are you sure?
can you reproduce it in the demo?

**Comment by joebordes** [comment]
I just tried on my development install and it worked as expected.
I see we fixed this on the 7th of July:  https://github.com/tsolucio/corebos/commit/54bb04303081175050554fe8b9e4ec8c0dabad25

Can you make sure your code is updated to past that date?

**Comment by partnerwerk** [comment]
Thank you for your hints, Joe. It looks like my ansible script did not copy the new files completely. So the source files got pulled from git but then not copied into the production folder. Since there was no eror message I blamed Corebos. Shame on me ;-) Now it is working again.

**Comment by joebordes** [comment]
Great!!
Have a nice weekend
