### ISSUE TITLE
When I ability Application_ListView_SearchColumns in To Dos - values in pick list not translated

### ISSUE THREAD

**Issue by slemernet** [tsolucio/corebos#853]
Values in column status and activity type not correctly translated when Search Columns activated
Label " Users " not translated too

![image](https://user-images.githubusercontent.com/47395137/91678331-b023c500-eb1b-11ea-9893-72065bbfcce0.png)

**Comment by joebordes** [comment]
we will not be fixing this as we are going to change the list view shortly
