### ISSUE TITLE
Mailscanner error task still runing in cron jobs 

### ISSUE THREAD

**Issue by slemernet** [tsolucio/corebos#870]
[INFO]: MailScanner - cron task had timedout as it is not completed last time it run- restarting
Scanning imap.gmail.com in progress

Warning: filesize(): stat failed for storage/mailscanner/168217_Funil de Vendas quarter_20200919100003.xls in /usr/share/master/modules/Settings/MailScanner/core/MailScannerAction.php on line 428

Warning: mb_convert_encoding(): Illegal character encoding specified in /usr/share/master/modules/Settings/MailScanner/core/MailRecord.php on line 158

Warning: mb_convert_encoding(): Illegal character encoding specified in /usr/share/master/modules/Settings/MailScanner/core/MailRecord.php on line 158

**Comment by joebordes** [comment]
Fixed the first warning.
Couldn't reproduce the second one. Open the issue again if you can get the $to and $from values when it fails.

Thanks
