### ISSUE TITLE
I run into a collation error when trying to set picklistvalues

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#934]
https://github.com/tsolucio/corebos/blob/24bc7f6a56ce8887ea8f4ee47533b89e666c4e26/vtlib/Vtiger/Field.php#L80

When trying to create a new field and setting the picklist values I run into `COLLATION 'utf8_bin' is not valid for CHARACTER SET 'binary'` because the code above tries to select using a `utf8_bin` collation. Do we need that? What is the advantage?

**Comment by Luke1982** [comment]
Hm, nevermind. I think there was something funky with my input, I filtered the array before sending it in. Now it's fine

**Comment by joebordes** [comment]
this is a world in itself, and we have to go there very soon: migrate to MySQL 8 and utf8mb4

https://medium.com/@manish_demblani/breaking-out-from-the-mysql-character-set-hell-24c6a306e1e5

to be continued...

**Comment by Luke1982** [comment]
Very interesting. This is a field in which I lack knowledge, thanks for the tip
