### ISSUE TITLE
Query not accepting parenthesis in where condition

### ISSUE THREAD

**Issue by bsikatti16** [tsolucio/corebos#943]
My  sql query is 

SELECT id, date_start, due_date, contact_id, assigned_user_id, parent_id, subject, time_start, time_end, description, eventstatus, activitytype, visibility, createdtime, modifiedtime FROM Events WHERE date_start >= '2020-10-01 00:00:00' AND date_start <= '2020-10-31 23:59:59' AND (assigned_user_id = '19x14' OR visibility = 'Public');

           {
            "success": false,
            "error": {
                "code": "QUERY_SYNTAX_ERROR",
                "message": "Syntax Error on line 1: token '(' Unexpected PARENOPEN((), expected one of: SEMICOLON"
            }

**Comment by joebordes** [comment]
what commit version is your coreBOS?

Please use cbCalendar for Calendar as Events is going to be eliminated shortly.

**Comment by joebordes** [comment]
I just tried the query above changing Events to cbCalendar and it seemed to work correctly. Try updating your coreBOS and let me know.

**Comment by joebordes** [comment]
open the issue again if you run into the issue again and let us know how it goes.
