### ISSUE TITLE
Inline validation doesn't send group tax percentage

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#944]
When I create a custom validation on one of the inventorymodules and then test it by editing the record in full the backend receives the entity (e.g. a SalesOrder) array that also includes the tax percentage per active tax (for example `$entity['tax1_group_percentage']`). But when I do an in-field edit, those array keys are not sent. I'd like to make sure the inline edit and full edit provide the validation backend with the same data.

**Comment by joebordes** [comment]
this is not how inline edit works. inline edit only sends the field being modified in all modules.
I don't think we should treat the inventory modules differently than all the others in this aspect, I prefer being consistent.

convince me

**Comment by joebordes** [comment]
closing this one
