### ISSUE TITLE
css problem on create new email from webmails

### ISSUE THREAD

**Issue by netme8** [tsolucio/corebos#962]
when creating a new email the top form field its ovelaped with the floating module info

**Comment by netme8** [comment]
![Screenshot_20201113_133618](https://user-images.githubusercontent.com/68737795/99072996-5b89d500-25b5-11eb-9493-ae4c5ad7e008.png)

**Comment by netme8** [comment]
![Screenshot_20201113_133618](https://user-images.githubusercontent.com/68737795/99073164-b4596d80-25b5-11eb-9d48-31c33498d4f9.png)

**Comment by netme8** [comment]
added on /include/LD/assets/styles/override_lds.css
for **temp** solution
 table {
  border-collapse: initial;
++  margin-top: 15px;
}

**Comment by Luke1982** [comment]
This is not a CSS issue. The 'new e-mail' part of the application in 'Smarty/templates/modules/MailManager/Mail.Send.tpl` loads the 'general.js' file multiple times, throwing off the JS measurements. @joebordes, if we can make [this](https://github.com/tsolucio/corebos/blob/master/Smarty/templates/modules/MailManager/Mail.Send.tpl#L9) line conditional on whether the template is loaded in a new window or in the application, it would work as normal.

**Comment by joebordes** [comment]
From what I see, the Mail.Send.tpl file is only loaded in Smarty/templates/modules/MailManager/index.tpl (twice as you indicate). 

Can we move [these two lines](https://github.com/tsolucio/corebos/blob/master/Smarty/templates/modules/MailManager/Mail.Send.tpl#L9:L10) from Mail.Send.tpl to Smarty/templates/modules/MailManager/index.tpl and fix the problem?

**Comment by Luke1982** [comment]
If I remember correctly that is half of the solution. The general.js file is also included in the main header of the application so the inclusion should just not take place at all in this template when the context is not 'a separate window'

**Comment by joebordes** [comment]
fixed with daa96319f2188ea3a3c125725ea0ee0aba052b03
