### ISSUE TITLE
When you delete workflow conditions, you can't save the workflow anymore

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#968]

**Comment by joebordes** [comment]
I cannot reproduce this. Neither in the master branch nor the denorm branch.
Please check that you have the latest version of javascript (cache)
If you are talking about a particular workflow TASK, please give more details. Also, try to reproduce in the demo and point to the failing workflow.

**Comment by Luke1982** [comment]
No this was a workflow, not a task. The installation is quite recent (maybe a month old), but I'll try and get some more information soon.

**Comment by joebordes** [comment]
closing this one
