### ISSUE TITLE
Workflow conditions disappeared 

### ISSUE THREAD

**Issue by netme8** [tsolucio/corebos#970]
i was suffering this issue 2 or 3 days and adding the condition for the workflow again

but now something its realy wrong when i get 

Failure:undefined

and i can't define workflow

**Comment by joebordes** [comment]
make sure your JS is up to date. clear the cache and load the service worker correctly.

it is almost for sure that because I am creating workflows every day, but if you think it isn't please reproduce it in the demo and give me steps to reproduce

**Comment by netme8** [comment]
how do i upgrade my js and service-worker? upload /include/js/general,js from last commit?

**Comment by joebordes** [comment]
open only one tab of corebos.
open the inspector console
reload
make sure you don't see any errors
wait a minute
reload again

**Comment by netme8** [comment]
this is the only error i get on the console -> index.php?module=ModTracker&action=ModTrackerAjax&file=getjslanguage” fue cargado a pesar de que su tipo MIME (“text/html”) no es un tipo MIME válido de JavaScript

**Comment by netme8** [comment]
the last relevant thing i did before i get that error was adding an attachment to one email workflow, after that everything worked

**Comment by joebordes** [comment]
so it is working now?

**Comment by netme8** [comment]
i still have the same error undefined, i have compared the module with the last
![workflow-diferences2](https://user-images.githubusercontent.com/68737795/100604771-4926cf80-3307-11eb-836b-4df64b4bf47c.png)
![workflow-diferences1](https://user-images.githubusercontent.com/68737795/100604773-49bf6600-3307-11eb-8ea4-eff981235eb2.png)

 version an i had find some diferences but when i had tryed to change ONLY the com_workflow_modue with last version a get error

**Comment by joebordes** [comment]
can you reproduce in the demo?

**Comment by netme8** [comment]
i have tryed without succes...

**Comment by joebordes** [comment]
try creating a new workflow, see if you can reproduce the issue

But you have to debug the issue on your install, there are just so many variables and things that can happen that there is no way we can help without connecting to your install and debugging it there. If you prefer to "just get it fixed" contact us, we have support and incident resolution services.

**Comment by joebordes** [comment]
feel free to reopen the issue if you can reproduce it

**Comment by netme8** [comment]
I am reaching to the point of the problem.... it's bad mysql response
i was havin troubles becouse the database now it's realy big and caches were getting filled
i noticed every time i add or edit a workflow loading the differnts fields were very slow
and at the end become a real issue that the condition field break on load
The solution comes when i clean up the database :-D
lot of thanks @joebordes for your help

**Comment by joebordes** [comment]
if you can share what "clear up the DB" means, it may be helpful. Like what queries were slow, what information did you delete or what indexes did you add...so we can add that in the product for everyone.

**Comment by netme8** [comment]
the main problem was that i had a backup database of 650mb already on the same server, so i delete it an everything start to work again, i think that the query cache was full
