### ISSUE TITLE
ProductAutocomplete doesn't send the account or contact ID

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#973]
When searching in the Product autocomplete, the actual contact and account ID's should get sent in the request. In stead, strings with the values 'account_id' and 'contact_id' get sent.

**Comment by joebordes** [comment]
most probably here: https://github.com/tsolucio/corebos/blob/master/include/js/Inventory.js#L1554
what does that function do?

**Comment by joebordes** [comment]
ah, I see, it is here:  https://github.com/tsolucio/corebos/blob/master/include/js/Inventory.js#L1547

you are getting the correct field name, but you have to go get the value of that field before sending it to coreBOS

**Comment by Luke1982** [comment]
PRing a fix now
