### ISSUE TITLE
Can't properly set discount back to zero in product autocomplete

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#975]
https://github.com/tsolucio/corebos/blob/ca8a2c599ada17d97726e57a24574c14f5b9d61b/include/js/Inventory.js#L2023

@joebordes you added this code [here](https://github.com/tsolucio/corebos/commit/35101fc31e306d2a224641c23b01e413646efe30), but there is a problem. I'm forking the discountline module and in it, I'm fixing what I believe to be a shortcoming: when you select a product that has (by some rule) been awarded a discount, but then select a _different_ product that has no discount, the previous discount stays in place.

I have added some code in the backend that explicitly sets the discount back to 0 when no applicable product is found, but that doesn't come through to the frontend since you explicitly tell the discount can't be zero here. Is there a reason behind this? I would like to remove that part of the condition.

**Comment by joebordes** [comment]
that doesn't sound like a shortcoming but an error that should be fixed in the discountline module, not forked. In any case, I will try to find some time to understand what this is all about as I don't remember anymore.
Sadly, that won't be any time soon. If there is anything you can do to make it easier for me to recover context I would appreciate.

**Comment by Luke1982** [comment]
I forked the discountline module because I didn't like the way it escalates its rules. In my opinion it is too eager to find a result preventing you from fine-tuning your discount. Of course the solution I used can to set the zero-discount on DiscountLine. [Here](https://github.com/Luke1982/PriceArrangement/commit/95f74227f2da80dea5dbbb64935b65d19f3a2c11) is the commit that does that.

What that commit does is explicitly return the discount as the number zero, even when there is no price/discount rule found. But the code you wrote in the commit I referenced ([this](https://github.com/tsolucio/corebos/commit/35101fc31e306d2a224641c23b01e413646efe30#diff-c36fd6468bcfeb35da78043294b6e023822a5d1fb4790e8442e43dd554918fe7R1895) line to be exact) doesn't accept an explicit zero discount, making it impossible for any price filter to (re)set the discount to zero.

So this way, selecting a product in the autocomplete that has a discount, but then changing that line to a product that has no discount, keeps the discount percentage from the previous product. What I'm proposing is to ditch the second part of the condition.

**Comment by joebordes** [comment]
would [this comit](https://github.com/tsolucio/corebos/compare/fix_975?expand=1) fix the issue?

**Comment by Luke1982** [comment]
From a glance, I think you need both. The one you reference and [this](https://github.com/Luke1982/PriceArrangement/commit/95f74227f2da80dea5dbbb64935b65d19f3a2c11) one. This is from memory, but as I recall the backend didn't provide the information and the front end didn't have a mechanism for receiving it

**Comment by joebordes** [comment]
Yes, I agree. This change in coreBOS and then whatever hook/code you add in the backend to send the information to coreBOS. 

What I am asking is; from the coreBOS side, the only change that is required is the one I made?

**Comment by Luke1982** [comment]
I believe so. The product autocomplete function in customerportalws uses the price filter and that should return an explicit int zero discount, which should trigger the code you referenced. It's been a couple of months since I wrote this but I believe that should do it.

**Comment by joebordes** [comment]
merged. give it a try when you can
thanks
