### ISSUE TITLE
Double JS file inclusion in SalesOrder (and possibly others)

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#976]
https://github.com/tsolucio/corebos/blob/ca8a2c599ada17d97726e57a24574c14f5b9d61b/Smarty/templates/Inventory/InventoryEditView.tpl#L12

This file is also included as a headerscript through a business action

**Comment by joebordes** [comment]
I eliminated the load in the code with this commit 0de0bac71a51b4a56daccb40e080ad707f38e27f

but I'm not quite sure about it, as those business actions were created in 2017 but I added this commit a2583b06be in 2019 to fix a bug.

sadly my git comment is useless as it doesn't state which function so I can't reproduce the bug I was trying to fix.

Let's keep an eye on it.
